import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade2Quizzes: Record<string, QuizConfig> = {
  "2-hundreds": createQuizConfig({
    id: "2-hundreds-quiz",
    title: "Understanding Hundreds Quiz",
    instructions: "Learn about hundreds place value!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many tens are in 100?",
        options: ["1", "10", "100", "0"],
        correctAnswer: "10",
        explanation: "100 = 10 tens. Each ten has 10 ones!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The number 352 has ___ hundreds.",
        correctAnswer: "3",
        explanation: "352 has 3 hundreds (300) + 5 tens (50) + 2 ones (2).",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What number has 4 hundreds, 2 tens, and 5 ones?",
        options: ["245", "425", "524", "452"],
        correctAnswer: "425",
        explanation: "4 hundreds (400) + 2 tens (20) + 5 ones (5) = 425!",
        points: 15,
      },
    ],
  }),

  "2-time": createQuizConfig({
    id: "2-time-quiz",
    title: "Telling Time Quiz",
    instructions: "Can you read the clock?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If the hour hand points to 3 and the minute hand points to 12, what time is it?",
        options: ["12:03", "3:00", "3:12", "12:00"],
        correctAnswer: "3:00",
        explanation: "When the minute hand is on 12, it's exactly that hour - 3:00!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "The short hand on a clock shows the hours.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The short hand shows hours, long hand shows minutes.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "There are ___ minutes in one hour.",
        correctAnswer: "60",
        explanation: "One hour has 60 minutes!",
        points: 10,
      },
    ],
  }),

  "2-character-analysis": createQuizConfig({
    id: "2-character-analysis-quiz",
    title: "Character Analysis Quiz",
    instructions: "Learn about story characters!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a character in a story?",
        options: ["The title", "A person or animal in the story", "The setting", "The ending"],
        correctAnswer: "A person or animal in the story",
        explanation: "Characters are the people, animals, or creatures in a story!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "We can learn about a character by what they say and do.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! A character's words and actions tell us about them.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If a character shares their toys, they are probably:",
        options: ["Mean", "Selfish", "Kind", "Scary"],
        correctAnswer: "Kind",
        explanation: "Sharing shows the character is kind and caring!",
        points: 15,
      },
    ],
  }),

  "2-habitats": createQuizConfig({
    id: "2-habitats-quiz",
    title: "Habitats Quiz",
    instructions: "Where do animals live?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a habitat?",
        options: ["A type of food", "A place where animals live", "A kind of weather", "An animal's name"],
        correctAnswer: "A place where animals live",
        explanation: "A habitat is a place where plants and animals live and find what they need!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each animal to its habitat:",
        options: ["Fish", "Camel", "Polar Bear"],
        matchTargets: ["Ocean", "Desert", "Arctic"],
        correctAnswer: ["Ocean", "Desert", "Arctic"],
        explanation: "Fish live in water, camels in deserts, polar bears in the Arctic!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Animals need food, water, and shelter from their habitat.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Habitats provide everything animals need to survive.",
        points: 10,
      },
    ],
  }),

  "2-food-chains": createQuizConfig({
    id: "2-food-chains-quiz",
    title: "Food Chains Quiz",
    instructions: "How do living things get energy?",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put this food chain in order:",
        options: ["Bird", "Sun", "Caterpillar", "Leaf"],
        correctAnswer: ["Sun", "Leaf", "Caterpillar", "Bird"],
        explanation: "Sun -> Leaf -> Caterpillar -> Bird. Energy flows from sun to plants to animals!",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Where does a food chain start?",
        options: ["Animals", "The Sun", "Humans", "Water"],
        correctAnswer: "The Sun",
        explanation: "All food chains start with the Sun! Plants use sunlight to make food.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Plants are called producers because they make their own food.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Plants produce food using sunlight, water, and air.",
        points: 10,
      },
    ],
  }),

  "2-wants-needs": createQuizConfig({
    id: "2-wants-needs-quiz",
    title: "Wants and Needs Quiz",
    instructions: "What do we need vs. what do we want?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which is a NEED?",
        options: ["Video games", "Food", "Toys", "Candy"],
        correctAnswer: "Food",
        explanation: "Food is a need - we must have it to live! Toys are wants.",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Is it a want or a need?",
        options: ["Water", "Shelter", "New bike"],
        matchTargets: ["Need", "Need", "Want"],
        correctAnswer: ["Need", "Need", "Want"],
        explanation: "Water and shelter are needs. A new bike is a want!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "We can live without our wants, but not without our needs.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Correct! Needs are for survival. Wants make life more fun!",
        points: 10,
      },
    ],
  }),

  "2-sequences": createQuizConfig({
    id: "2-sequences-quiz",
    title: "Sequences Quiz",
    instructions: "Put steps in the right order!",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put these steps for making a sandwich in order:",
        options: ["Add filling", "Put bread on top", "Get two slices of bread", "Eat the sandwich"],
        correctAnswer: ["Get two slices of bread", "Add filling", "Put bread on top", "Eat the sandwich"],
        explanation: "First get bread, add filling, close it, then eat!",
        points: 20,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In a sequence, order matters.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Sequences are steps that must be done in a specific order.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What comes first when brushing your teeth?",
        options: ["Rinse your mouth", "Put toothpaste on brush", "Brush your teeth", "Put away the brush"],
        correctAnswer: "Put toothpaste on brush",
        explanation: "First put toothpaste on, then brush, then rinse!",
        points: 10,
      },
    ],
  }),
};
