import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade5Quizzes: Record<string, QuizConfig> = {
  "5-multiply-fractions": createQuizConfig({
    id: "5-multiply-fractions-quiz",
    title: "Multiplying Fractions Quiz",
    instructions: "Practice multiplying fractions!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 1/2 x 1/4?",
        options: ["1/2", "1/6", "1/8", "2/4"],
        correctAnswer: "1/8",
        explanation: "Multiply numerators: 1 x 1 = 1. Multiply denominators: 2 x 4 = 8. Answer: 1/8",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "2/3 x 3/4 = ___ (write as a simplified fraction like 1/2)",
        correctAnswer: "1/2",
        explanation: "(2x3)/(3x4) = 6/12 = 1/2",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "When you multiply two fractions less than 1, the answer is smaller than either fraction.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Multiplying fractions less than 1 gives a smaller result.",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "What is 3/5 x 2/3?",
        options: ["6/15", "5/8", "2/5", "6/8"],
        correctAnswer: "2/5",
        explanation: "(3x2)/(5x3) = 6/15 = 2/5 (simplified by dividing by 3)",
        points: 15,
      },
    ],
  }),

  "5-multiply-decimals": createQuizConfig({
    id: "5-multiply-decimals-quiz",
    title: "Multiplying Decimals Quiz",
    instructions: "Practice multiplying decimal numbers!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 0.5 x 0.4?",
        options: ["2.0", "0.20", "0.9", "0.02"],
        correctAnswer: "0.20",
        explanation: "5 x 4 = 20, then count 2 decimal places total = 0.20",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "1.5 x 2 = ___",
        correctAnswer: "3",
        explanation: "1.5 x 2 = 3.0 or just 3",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is 2.5 x 0.4?",
        options: ["1.0", "0.1", "10", "0.01"],
        correctAnswer: "1.0",
        explanation: "25 x 4 = 100, then count 2 decimal places = 1.00 = 1.0",
        points: 10,
      },
    ],
  }),

  "5-literary-devices": createQuizConfig({
    id: "5-literary-devices-quiz",
    title: "Literary Devices Quiz",
    instructions: "Identify literary devices in writing!",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the literary device to the example:",
        options: ["Simile", "Metaphor", "Personification", "Alliteration"],
        matchTargets: ["Fast as lightning", "Life is a journey", "The wind whispered", "Peter Piper picked"],
        correctAnswer: ["Fast as lightning", "Life is a journey", "The wind whispered", "Peter Piper picked"],
        explanation: "Similes use 'like' or 'as', metaphors don't, personification gives human qualities, alliteration repeats sounds.",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "'The stars danced in the night sky' is an example of:",
        options: ["Simile", "Metaphor", "Personification", "Hyperbole"],
        correctAnswer: "Personification",
        explanation: "Stars can't actually dance - giving them human actions is personification.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is hyperbole?",
        options: ["A comparison using 'like'", "Extreme exaggeration", "Repeating sounds", "A type of rhyme"],
        correctAnswer: "Extreme exaggeration",
        explanation: "Hyperbole is extreme exaggeration for effect, like 'I'm so hungry I could eat a horse.'",
        points: 10,
      },
    ],
  }),

  "5-sources": createQuizConfig({
    id: "5-sources-quiz",
    title: "Research Sources Quiz",
    instructions: "Learn about finding and using sources!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a primary source?",
        options: ["A textbook about history", "An encyclopedia", "A letter written during an event", "A documentary"],
        correctAnswer: "A letter written during an event",
        explanation: "Primary sources are original documents from the time being studied.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "You should always use the first website you find in your research.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "No! Always check if sources are reliable and accurate.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which is a reliable source for a research project?",
        options: ["A random blog", "Wikipedia alone", "A government website (.gov)", "Social media posts"],
        correctAnswer: "A government website (.gov)",
        explanation: "Government websites (.gov) are typically reliable and factual.",
        points: 10,
      },
    ],
  }),

  "5-states-of-matter": createQuizConfig({
    id: "5-states-of-matter-quiz",
    title: "States of Matter Quiz",
    instructions: "Understand solids, liquids, and gases!",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match each property to the correct state of matter:",
        options: ["Fixed shape and volume", "Fixed volume but takes container shape", "No fixed shape or volume"],
        matchTargets: ["Solid", "Liquid", "Gas"],
        correctAnswer: ["Solid", "Liquid", "Gas"],
        explanation: "Solids keep their shape, liquids flow, gases expand to fill containers.",
        points: 15,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What happens to particles when a solid is heated?",
        options: ["They slow down", "They move faster", "They disappear", "They multiply"],
        correctAnswer: "They move faster",
        explanation: "Adding heat gives particles more energy, making them move faster.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "When water freezes, it changes from a liquid to a ___.",
        correctAnswer: "solid",
        explanation: "Freezing is the change from liquid to solid.",
        points: 10,
      },
    ],
  }),

  "5-chemical-changes": createQuizConfig({
    id: "5-chemical-changes-quiz",
    title: "Chemical Changes Quiz",
    instructions: "Learn about chemical vs physical changes!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which is an example of a chemical change?",
        options: ["Ice melting", "Wood burning", "Paper being cut", "Water evaporating"],
        correctAnswer: "Wood burning",
        explanation: "Burning creates new substances (ash, smoke) - it's irreversible!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Is it a physical or chemical change?",
        options: ["Rusting iron", "Dissolving sugar", "Baking a cake"],
        matchTargets: ["Chemical", "Physical", "Chemical"],
        correctAnswer: ["Chemical", "Physical", "Chemical"],
        explanation: "Rusting and baking create new substances. Dissolving sugar is physical - you can get it back!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Chemical changes can usually be reversed easily.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Chemical changes are typically irreversible - you can't unburn wood!",
        points: 10,
      },
    ],
  }),

  "5-food-webs": createQuizConfig({
    id: "5-food-webs-quiz",
    title: "Food Webs Quiz",
    instructions: "Understand how organisms are connected!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How is a food web different from a food chain?",
        options: ["It's smaller", "It shows many connected food chains", "It only includes plants", "It has no producers"],
        correctAnswer: "It shows many connected food chains",
        explanation: "Food webs show how multiple food chains connect and overlap.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "If one species disappears from a food web, it can affect many other species.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Species in a food web are interconnected, so changes ripple through.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What role do decomposers play in a food web?",
        options: ["They eat only plants", "They break down dead organisms", "They produce food", "They eat only meat"],
        correctAnswer: "They break down dead organisms",
        explanation: "Decomposers (like fungi and bacteria) break down dead matter and recycle nutrients.",
        points: 10,
      },
    ],
  }),

  "5-colonial-period": createQuizConfig({
    id: "5-colonial-period-quiz",
    title: "Colonial America Quiz",
    instructions: "Test your knowledge of colonial times!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What was the first permanent English settlement in America?",
        options: ["Plymouth", "Jamestown", "Boston", "Philadelphia"],
        correctAnswer: "Jamestown",
        explanation: "Jamestown, Virginia was founded in 1607.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Why did the Pilgrims come to America?",
        options: ["To find gold", "For religious freedom", "To explore", "For vacation"],
        correctAnswer: "For religious freedom",
        explanation: "The Pilgrims wanted to practice their religion freely.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The 13 colonies were controlled by which country? ___",
        correctAnswer: "England",
        explanation: "The 13 colonies were British (English) colonies.",
        points: 10,
      },
    ],
  }),

  "5-revolution": createQuizConfig({
    id: "5-revolution-quiz",
    title: "American Revolution Quiz",
    instructions: "Learn about American independence!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What document declared American independence from Britain?",
        options: ["The Constitution", "The Bill of Rights", "The Declaration of Independence", "The Mayflower Compact"],
        correctAnswer: "The Declaration of Independence",
        explanation: "The Declaration of Independence was signed on July 4, 1776.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "'No taxation without representation' meant colonists wanted:",
        options: ["Lower taxes", "No government", "A say in laws that affected them", "More British soldiers"],
        correctAnswer: "A say in laws that affected them",
        explanation: "Colonists wanted representation in Parliament if they were going to be taxed.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The Boston ___ Party was a protest against British tea taxes.",
        correctAnswer: "Tea",
        explanation: "The Boston Tea Party (1773) was when colonists dumped tea into the harbor.",
        points: 10,
      },
    ],
  }),

  "5-data-visualization": createQuizConfig({
    id: "5-data-visualization-quiz",
    title: "Data Visualization Quiz",
    instructions: "Learn about presenting data visually!",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the chart type to its best use:",
        options: ["Bar chart", "Line graph", "Pie chart"],
        matchTargets: ["Comparing categories", "Showing change over time", "Showing parts of a whole"],
        correctAnswer: ["Comparing categories", "Showing change over time", "Showing parts of a whole"],
        explanation: "Different charts work better for different types of data!",
        points: 15,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which chart would best show how temperature changed throughout a day?",
        options: ["Pie chart", "Bar chart", "Line graph", "Table"],
        correctAnswer: "Line graph",
        explanation: "Line graphs are best for showing changes over time.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A pie chart should always show percentages that add up to 100%.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Pie charts show parts of a whole, which must total 100%.",
        points: 10,
      },
    ],
  }),

  "5-spreadsheets": createQuizConfig({
    id: "5-spreadsheets-quiz",
    title: "Spreadsheets Quiz",
    instructions: "Learn about spreadsheet basics!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a cell in a spreadsheet?",
        options: ["A row", "A column", "The box where a row and column meet", "A formula"],
        correctAnswer: "The box where a row and column meet",
        explanation: "A cell is the intersection of a row and column, like A1 or B3.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "In a spreadsheet, columns are labeled with ___ (letters or numbers).",
        correctAnswer: "letters",
        explanation: "Columns are A, B, C, etc. Rows are 1, 2, 3, etc.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What symbol typically starts a formula in a spreadsheet?",
        options: ["#", "=", "@", "$"],
        correctAnswer: "=",
        explanation: "Formulas start with = like =A1+B1 or =SUM(A1:A10)",
        points: 10,
      },
    ],
  }),
};
