/**
 * Quiz Data
 * Sample quiz configurations for curriculum lessons
 */

import type { QuizConfig } from "./types";

/**
 * Quiz configurations mapped by lesson ID
 */
export const quizConfigs: Record<string, QuizConfig> = {
  // Kindergarten Math - Counting
  "k-count-1-10": {
    id: "k-count-1-10-quiz",
    title: "Counting 1 to 10 Quiz",
    instructions: "Answer these questions about counting from 1 to 10.",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many apples are in this picture? 🍎🍎🍎",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3",
        explanation: "Count each apple: 1, 2, 3. There are 3 apples!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What number comes after 5?",
        options: ["4", "5", "6", "7"],
        correctAnswer: "6",
        explanation: "After 5 comes 6. The sequence is: 5, 6, 7...",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The number 8 is bigger than the number 6.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 8 is bigger than 6 because it comes after 6 when counting.",
        points: 10,
      },
      {
        id: "q4",
        type: "ordering",
        question: "Put these numbers in order from smallest to biggest:",
        options: ["3", "1", "5", "2", "4"],
        correctAnswer: ["1", "2", "3", "4", "5"],
        explanation: "The correct order is: 1, 2, 3, 4, 5",
        points: 20,
      },
    ],
  },

  // Kindergarten Math - 2D Shapes
  "k-2d-shapes": {
    id: "k-2d-shapes-quiz",
    title: "2D Shapes Quiz",
    instructions: "Let's see what you learned about shapes!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many sides does a triangle have?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3",
        explanation: "A triangle has 3 sides. Tri means three!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each shape to its number of sides:",
        options: ["Circle", "Triangle", "Square", "Rectangle"],
        matchTargets: ["0 sides", "3 sides", "4 sides", "4 sides"],
        correctAnswer: ["0 sides", "3 sides", "4 sides", "4 sides"],
        explanation: "Circles have no straight sides, triangles have 3, and both squares and rectangles have 4 sides.",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A circle has corners.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "A circle is round and has no corners at all!",
        points: 10,
      },
    ],
  },

  // Kindergarten Math - 3D Shapes
  "k-3d-shapes": {
    id: "k-3d-shapes-quiz",
    title: "3D Shapes Quiz",
    instructions: "Test your knowledge of 3D shapes!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which shape looks like a ball?",
        options: ["Cube", "Sphere", "Cylinder", "Cone"],
        correctAnswer: "Sphere",
        explanation: "A sphere is round like a ball!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "A box is shaped like a:",
        options: ["Sphere", "Cone", "Cube", "Cylinder"],
        correctAnswer: "Cube",
        explanation: "A cube has 6 flat faces, just like a box!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A cone has a flat bottom and a point at the top.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Think of an ice cream cone - flat on bottom, pointy on top.",
        points: 10,
      },
    ],
  },

  // Kindergarten Math - Counting 11-20
  "k-count-11-20": {
    id: "k-count-11-20-quiz",
    title: "Counting 11 to 20 Quiz",
    instructions: "Let's count bigger numbers! 🔢",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What number comes after 10?",
        options: ["9", "10", "11", "12"],
        correctAnswer: "11",
        explanation: "After 10 comes 11. Keep counting!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "How many stars? ⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐",
        options: ["13", "14", "15", "16"],
        correctAnswer: "15",
        explanation: "Count each star: there are 15 stars!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The number 18 comes before 17.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "18 comes AFTER 17, not before!",
        points: 10,
      },
      {
        id: "q4",
        type: "ordering",
        question: "Put these numbers in order from smallest to biggest:",
        options: ["15", "12", "18", "11"],
        correctAnswer: ["11", "12", "15", "18"],
        explanation: "The correct order is: 11, 12, 15, 18",
        points: 20,
      },
    ],
  },

  // Kindergarten Math - Addition Introduction
  "k-addition-intro": {
    id: "k-addition-intro-quiz",
    title: "Introduction to Addition Quiz",
    instructions: "Let's practice adding! ➕",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "🍎🍎 + 🍎 = How many apples?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3",
        explanation: "2 apples plus 1 apple equals 3 apples!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "1 + 1 = ___",
        correctAnswer: "2",
        explanation: "1 plus 1 equals 2!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "2 + 2 = ?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "4",
        explanation: "2 plus 2 equals 4!",
        points: 10,
      },
      {
        id: "q4",
        type: "true_false",
        question: "When we add, we put things together.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Adding means putting things together to get more.",
        points: 10,
      },
    ],
  },

  // Kindergarten Math - Subtraction Introduction
  "k-subtraction-intro": {
    id: "k-subtraction-intro-quiz",
    title: "Introduction to Subtraction Quiz",
    instructions: "Let's practice taking away! ➖",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "You have 3 cookies 🍪🍪🍪. You eat 1. How many are left?",
        options: ["1", "2", "3", "4"],
        correctAnswer: "2",
        explanation: "3 cookies minus 1 cookie equals 2 cookies!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "4 - 1 = ___",
        correctAnswer: "3",
        explanation: "4 minus 1 equals 3!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "When we subtract, we take things away.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Subtracting means taking away to get less.",
        points: 10,
      },
    ],
  },

  // Kindergarten Reading - Alphabet
  "k-alphabet": {
    id: "k-alphabet-quiz",
    title: "The Alphabet Quiz",
    instructions: "Let's test what you know about letters! 🔤",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What letter comes after A?",
        options: ["C", "B", "D", "Z"],
        correctAnswer: "B",
        explanation: "A, B, C! B comes after A.",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these letters in ABC order:",
        options: ["C", "A", "D", "B"],
        correctAnswer: ["A", "B", "C", "D"],
        explanation: "The alphabet goes: A, B, C, D!",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The letter Z is the last letter of the alphabet.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The alphabet ends with Z.",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "How many letters are in the alphabet?",
        options: ["20", "24", "26", "30"],
        correctAnswer: "26",
        explanation: "There are 26 letters from A to Z!",
        points: 10,
      },
    ],
  },

  // Kindergarten Reading - Letter Sounds
  "k-letter-sounds": {
    id: "k-letter-sounds-quiz",
    title: "Letter Sounds Quiz",
    instructions: "Match letters with their sounds! 🔊",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What sound does the letter S make?",
        options: ["sss (like a snake)", "mmm", "bbb", "rrr"],
        correctAnswer: "sss (like a snake)",
        explanation: "S makes the 'sss' sound, like a snake!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which letter makes the 'mmmm' sound?",
        options: ["N", "M", "B", "P"],
        correctAnswer: "M",
        explanation: "M makes the 'mmmm' sound!",
        points: 10,
      },
      {
        id: "q3",
        type: "matching",
        question: "Match each letter to its sound:",
        options: ["B", "C", "D"],
        matchTargets: ["buh", "kuh", "duh"],
        correctAnswer: ["buh", "kuh", "duh"],
        explanation: "B says 'buh', C says 'kuh', D says 'duh'!",
        points: 15,
      },
    ],
  },

  // Kindergarten Reading - Rhyming
  "k-rhyming": {
    id: "k-rhyming-quiz",
    title: "Rhyming Words Quiz",
    instructions: "Find words that sound alike at the end! 🎵",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which word rhymes with CAT?",
        options: ["Dog", "Hat", "Cup", "Run"],
        correctAnswer: "Hat",
        explanation: "Cat and Hat both end with 'at' - they rhyme!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which word rhymes with SUN?",
        options: ["Moon", "Fun", "Star", "Hot"],
        correctAnswer: "Fun",
        explanation: "Sun and Fun both end with 'un' - they rhyme!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Dog and Frog rhyme.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Dog and Frog both end with 'og'.",
        points: 10,
      },
    ],
  },

  // Kindergarten Science - Weather Types
  "k-weather-types": {
    id: "k-weather-types-quiz",
    title: "Types of Weather Quiz",
    instructions: "What do you know about weather? ☀️🌧️",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What do we call it when water falls from the sky?",
        options: ["Sunny", "Rain", "Wind", "Snow"],
        correctAnswer: "Rain",
        explanation: "When water drops fall from clouds, it's called rain!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match the weather to its picture:",
        options: ["☀️", "🌧️", "❄️"],
        matchTargets: ["Sunny", "Rainy", "Snowy"],
        correctAnswer: ["Sunny", "Rainy", "Snowy"],
        explanation: "Sun means sunny, raindrops mean rainy, snowflake means snowy!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Clouds can be in the sky on sunny days.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! We can have sun and some clouds at the same time.",
        points: 10,
      },
    ],
  },

  // Kindergarten Science - Seasons
  "k-seasons": {
    id: "k-seasons-quiz",
    title: "Seasons Quiz",
    instructions: "Learn about the four seasons! 🌸☀️🍂❄️",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In which season do leaves fall from trees?",
        options: ["Spring", "Summer", "Fall", "Winter"],
        correctAnswer: "Fall",
        explanation: "In fall (autumn), leaves change color and fall from trees!",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put the seasons in order, starting with Spring:",
        options: ["Winter", "Fall", "Summer", "Spring"],
        correctAnswer: ["Spring", "Summer", "Fall", "Winter"],
        explanation: "The seasons go: Spring, Summer, Fall, Winter!",
        points: 20,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which season is the coldest?",
        options: ["Spring", "Summer", "Fall", "Winter"],
        correctAnswer: "Winter",
        explanation: "Winter is the coldest season with snow in many places!",
        points: 10,
      },
    ],
  },

  // Kindergarten Science - Living vs Non-Living
  "k-living-nonliving": {
    id: "k-living-nonliving-quiz",
    title: "Living vs Non-Living Quiz",
    instructions: "Can you tell what's alive? 🌱🪨",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which one is a living thing?",
        options: ["Rock", "Tree", "Car", "Table"],
        correctAnswer: "Tree",
        explanation: "Trees are living! They grow, need water, and make seeds.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A dog is a living thing.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Dogs are alive - they eat, breathe, grow, and move!",
        points: 10,
      },
      {
        id: "q3",
        type: "matching",
        question: "Is it living or non-living?",
        options: ["Cat", "Flower", "Rock"],
        matchTargets: ["Living", "Living", "Non-living"],
        correctAnswer: ["Living", "Living", "Non-living"],
        explanation: "Cats and flowers are living. Rocks are non-living!",
        points: 15,
      },
    ],
  },

  // Kindergarten History - Community Helpers
  "k-helpers": {
    id: "k-helpers-quiz",
    title: "Community Helpers Quiz",
    instructions: "Who helps in our community? 👨‍🚒👩‍⚕️",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Who helps put out fires?",
        options: ["Teacher", "Doctor", "Firefighter", "Chef"],
        correctAnswer: "Firefighter",
        explanation: "Firefighters are brave helpers who put out fires!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each helper to what they do:",
        options: ["Doctor", "Teacher", "Police Officer"],
        matchTargets: ["Helps sick people", "Helps us learn", "Keeps us safe"],
        correctAnswer: ["Helps sick people", "Helps us learn", "Keeps us safe"],
        explanation: "Doctors help sick people, teachers help us learn, police keep us safe!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Librarians help us find books.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Librarians are helpers who work with books!",
        points: 10,
      },
    ],
  },

  // Kindergarten Technology - Parts of Computer
  "k-parts-computer": {
    id: "k-parts-computer-quiz",
    title: "Parts of a Computer Quiz",
    instructions: "What are the parts of a computer? 💻",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What part of the computer shows pictures and words?",
        options: ["Mouse", "Keyboard", "Screen/Monitor", "Printer"],
        correctAnswer: "Screen/Monitor",
        explanation: "The screen (or monitor) shows us pictures and words!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What do we use to type letters?",
        options: ["Mouse", "Keyboard", "Screen", "Speaker"],
        correctAnswer: "Keyboard",
        explanation: "We type letters and numbers on the keyboard!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A mouse helps us click and point on the screen.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! We use the mouse to move the pointer and click!",
        points: 10,
      },
    ],
  },

  // Grade 1 Math - Tens and Ones
  "1-tens-ones": {
    id: "1-tens-ones-quiz",
    title: "Tens and Ones Quiz",
    instructions: "Let's learn about place value!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In the number 25, how many tens are there?",
        options: ["2", "5", "25", "7"],
        correctAnswer: "2",
        explanation: "25 has 2 tens (20) and 5 ones (5). 20 + 5 = 25!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The number 34 has 3 tens and ___ ones.",
        correctAnswer: "4",
        explanation: "34 = 30 + 4, so there are 4 ones!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What number has 4 tens and 7 ones?",
        options: ["47", "74", "11", "41"],
        correctAnswer: "47",
        explanation: "4 tens = 40, plus 7 ones = 47!",
        points: 10,
      },
      {
        id: "q4",
        type: "true_false",
        question: "The number 50 has 5 tens and 0 ones.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 50 = 5 tens (50) + 0 ones.",
        points: 10,
      },
    ],
  },

  // Grade 1 Math - Addition within 20
  "1-add-within-20": {
    id: "1-add-within-20-quiz",
    title: "Addition within 20 Quiz",
    instructions: "Practice adding numbers up to 20!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "fill_blank",
        question: "8 + 5 = ___",
        correctAnswer: "13",
        explanation: "8 + 5 = 13. You can count on: 8... 9, 10, 11, 12, 13!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What is 9 + 7?",
        options: ["14", "15", "16", "17"],
        correctAnswer: "16",
        explanation: "9 + 7 = 16. Think: 9 + 1 = 10, then 10 + 6 = 16!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which addition equals 15?",
        options: ["6 + 8", "7 + 8", "9 + 5", "8 + 8"],
        correctAnswer: "7 + 8",
        explanation: "7 + 8 = 15!",
        points: 15,
      },
    ],
  },

  // Grade 1 Reading - Short Vowels
  "1-short-vowels": {
    id: "1-short-vowels-quiz",
    title: "Short Vowels Quiz",
    instructions: "Listen for short vowel sounds!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which word has a short 'a' sound?",
        options: ["cake", "cat", "car", "cape"],
        correctAnswer: "cat",
        explanation: "Cat has the short 'a' sound like in 'apple'!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match words with the same short vowel sound:",
        options: ["bed", "pig", "hot"],
        matchTargets: ["short e", "short i", "short o"],
        correctAnswer: ["short e", "short i", "short o"],
        explanation: "Bed has short e, pig has short i, hot has short o!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The word 'cup' has a short 'u' sound.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Cup has the short 'u' sound like in 'umbrella'.",
        points: 10,
      },
    ],
  },

  // Grade 1 Science - Light Sources
  "1-light-sources": {
    id: "1-light-sources-quiz",
    title: "Light Sources Quiz",
    instructions: "Where does light come from?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the biggest source of light for Earth?",
        options: ["Moon", "Stars", "Sun", "Lamp"],
        correctAnswer: "Sun",
        explanation: "The Sun is our biggest and brightest source of light!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A flashlight makes its own light.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! A flashlight is a light source - it makes light!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which is NOT a light source?",
        options: ["Candle", "Mirror", "Lamp", "Fire"],
        correctAnswer: "Mirror",
        explanation: "A mirror reflects light but doesn't make its own light.",
        points: 15,
      },
    ],
  },

  // Grade 1 Science - Day and Night
  "1-day-night": {
    id: "1-day-night-quiz",
    title: "Day and Night Quiz",
    instructions: "Why do we have day and night?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What makes daytime bright?",
        options: ["Moon", "Sun", "Stars", "Clouds"],
        correctAnswer: "Sun",
        explanation: "The Sun shines on Earth and makes daytime bright!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Earth spins around, which causes day and night.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! As Earth spins, different parts face the Sun.",
        points: 10,
      },
      {
        id: "q3",
        type: "ordering",
        question: "Put these in order from morning to night:",
        options: ["Sunset", "Sunrise", "Noon", "Midnight"],
        correctAnswer: ["Sunrise", "Noon", "Sunset", "Midnight"],
        explanation: "A day goes: sunrise, noon, sunset, midnight!",
        points: 20,
      },
    ],
  },

  // Grade 1 History - Rules and Laws
  "1-rules-laws": {
    id: "1-rules-laws-quiz",
    title: "Rules and Laws Quiz",
    instructions: "Why do we have rules?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Why do we have rules?",
        options: ["To have fun", "To keep us safe", "To make us sad", "To waste time"],
        correctAnswer: "To keep us safe",
        explanation: "Rules help keep everyone safe and things fair!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "It's a rule to raise your hand before speaking in class.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! This rule helps everyone get a turn to speak.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is a law?",
        options: ["A game", "A rule made by the government", "A toy", "A book"],
        correctAnswer: "A rule made by the government",
        explanation: "Laws are rules that everyone in a community must follow.",
        points: 15,
      },
    ],
  },

  // Grade 1 Technology - Internet Safety
  "1-internet-safety": {
    id: "1-internet-safety-quiz",
    title: "Internet Safety Quiz",
    instructions: "Stay safe online! 🔒",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Should you share your password with friends?",
        options: ["Yes, always", "No, never", "Only best friends", "Only online"],
        correctAnswer: "No, never",
        explanation: "Passwords are secret! Only share with parents.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "You should tell a grown-up if something online makes you feel scared or sad.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Always tell a trusted adult if something online upsets you.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What should you NOT share online?",
        options: ["Your favorite color", "Your full name and address", "Your favorite animal", "Your hobby"],
        correctAnswer: "Your full name and address",
        explanation: "Never share personal info like your full name, address, or school online!",
        points: 15,
      },
    ],
  },

  // Grade 2 Math - Understanding Hundreds
  "2-hundreds": {
    id: "2-hundreds-quiz",
    title: "Understanding Hundreds Quiz",
    instructions: "Learn about hundreds place value!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many tens are in 100?",
        options: ["1", "10", "100", "0"],
        correctAnswer: "10",
        explanation: "100 = 10 tens. Each ten has 10 ones!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The number 352 has ___ hundreds.",
        correctAnswer: "3",
        explanation: "352 has 3 hundreds (300) + 5 tens (50) + 2 ones (2).",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What number has 4 hundreds, 2 tens, and 5 ones?",
        options: ["245", "425", "524", "452"],
        correctAnswer: "425",
        explanation: "4 hundreds (400) + 2 tens (20) + 5 ones (5) = 425!",
        points: 15,
      },
    ],
  },

  // Grade 2 Math - Telling Time
  "2-time": {
    id: "2-time-quiz",
    title: "Telling Time Quiz",
    instructions: "Can you read the clock? ⏰",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If the hour hand points to 3 and the minute hand points to 12, what time is it?",
        options: ["12:03", "3:00", "3:12", "12:00"],
        correctAnswer: "3:00",
        explanation: "When the minute hand is on 12, it's exactly that hour - 3:00!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "The short hand on a clock shows the hours.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The short hand shows hours, long hand shows minutes.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "There are ___ minutes in one hour.",
        correctAnswer: "60",
        explanation: "One hour has 60 minutes!",
        points: 10,
      },
    ],
  },

  // Grade 2 Reading - Character Analysis
  "2-character-analysis": {
    id: "2-character-analysis-quiz",
    title: "Character Analysis Quiz",
    instructions: "Learn about story characters!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a character in a story?",
        options: ["The title", "A person or animal in the story", "The setting", "The ending"],
        correctAnswer: "A person or animal in the story",
        explanation: "Characters are the people, animals, or creatures in a story!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "We can learn about a character by what they say and do.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! A character's words and actions tell us about them.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If a character shares their toys, they are probably:",
        options: ["Mean", "Selfish", "Kind", "Scary"],
        correctAnswer: "Kind",
        explanation: "Sharing shows the character is kind and caring!",
        points: 15,
      },
    ],
  },

  // Grade 2 Science - Habitats
  "2-habitats": {
    id: "2-habitats-quiz",
    title: "Habitats Quiz",
    instructions: "Where do animals live? 🏠🌲",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a habitat?",
        options: ["A type of food", "A place where animals live", "A kind of weather", "An animal's name"],
        correctAnswer: "A place where animals live",
        explanation: "A habitat is a place where plants and animals live and find what they need!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each animal to its habitat:",
        options: ["Fish", "Camel", "Polar Bear"],
        matchTargets: ["Ocean", "Desert", "Arctic"],
        correctAnswer: ["Ocean", "Desert", "Arctic"],
        explanation: "Fish live in water, camels in deserts, polar bears in the Arctic!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Animals need food, water, and shelter from their habitat.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Habitats provide everything animals need to survive.",
        points: 10,
      },
    ],
  },

  // Grade 2 Science - Food Chains
  "2-food-chains": {
    id: "2-food-chains-quiz",
    title: "Food Chains Quiz",
    instructions: "How do living things get energy? 🌱🐛🐦",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put this food chain in order:",
        options: ["Bird", "Sun", "Caterpillar", "Leaf"],
        correctAnswer: ["Sun", "Leaf", "Caterpillar", "Bird"],
        explanation: "Sun → Leaf → Caterpillar → Bird. Energy flows from sun to plants to animals!",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Where does a food chain start?",
        options: ["Animals", "The Sun", "Humans", "Water"],
        correctAnswer: "The Sun",
        explanation: "All food chains start with the Sun! Plants use sunlight to make food.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Plants are called producers because they make their own food.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Plants produce food using sunlight, water, and air.",
        points: 10,
      },
    ],
  },

  // Grade 2 History - Wants and Needs
  "2-wants-needs": {
    id: "2-wants-needs-quiz",
    title: "Wants and Needs Quiz",
    instructions: "What do we need vs. what do we want?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which is a NEED?",
        options: ["Video games", "Food", "Toys", "Candy"],
        correctAnswer: "Food",
        explanation: "Food is a need - we must have it to live! Toys are wants.",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Is it a want or a need?",
        options: ["Water", "Shelter", "New bike"],
        matchTargets: ["Need", "Need", "Want"],
        correctAnswer: ["Need", "Need", "Want"],
        explanation: "Water and shelter are needs. A new bike is a want!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "We can live without our wants, but not without our needs.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Correct! Needs are for survival. Wants make life more fun!",
        points: 10,
      },
    ],
  },

  // Grade 2 Technology - Sequences
  "2-sequences": {
    id: "2-sequences-quiz",
    title: "Sequences Quiz",
    instructions: "Put steps in the right order! 📝",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put these steps for making a sandwich in order:",
        options: ["Add filling", "Put bread on top", "Get two slices of bread", "Eat the sandwich"],
        correctAnswer: ["Get two slices of bread", "Add filling", "Put bread on top", "Eat the sandwich"],
        explanation: "First get bread, add filling, close it, then eat!",
        points: 20,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In a sequence, order matters.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Sequences are steps that must be done in a specific order.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What comes first when brushing your teeth?",
        options: ["Rinse your mouth", "Put toothpaste on brush", "Brush your teeth", "Put away the brush"],
        correctAnswer: "Put toothpaste on brush",
        explanation: "First put toothpaste on, then brush, then rinse!",
        points: 10,
      },
    ],
  },

  // Grade 3 - Multiplication Introduction
  "3-mult-intro": {
    id: "3-mult-intro-quiz",
    title: "Introduction to Multiplication Quiz",
    instructions: "Show what you learned about multiplication!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 3 × 4?",
        options: ["7", "10", "12", "14"],
        correctAnswer: "12",
        explanation: "3 × 4 means 3 groups of 4, which equals 12.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "5 × 2 = ___",
        correctAnswer: "10",
        explanation: "5 × 2 = 10. Think of it as 5 + 5!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If you have 4 bags with 3 apples in each bag, how many apples do you have in total?",
        options: ["7", "10", "12", "15"],
        correctAnswer: "12",
        explanation: "4 bags × 3 apples = 12 apples total.",
        points: 15,
      },
      {
        id: "q4",
        type: "true_false",
        question: "2 × 6 gives the same answer as 6 × 2.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! This is called the commutative property. Order doesn't matter in multiplication.",
        points: 10,
      },
      {
        id: "q5",
        type: "ordering",
        question: "Put these products in order from smallest to largest:",
        options: ["2×5", "3×3", "4×2", "1×6"],
        correctAnswer: ["1×6", "4×2", "3×3", "2×5"],
        explanation: "1×6=6, 4×2=8, 3×3=9, 2×5=10. So the order is: 6, 8, 9, 10.",
        points: 15,
      },
    ],
  },

  // Grade 3 - Fractions Introduction
  "3-fractions-intro": {
    id: "3-fractions-intro-quiz",
    title: "Introduction to Fractions Quiz",
    instructions: "Test your understanding of fractions!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If a pizza is cut into 4 equal pieces and you eat 1 piece, what fraction did you eat?",
        options: ["1/2", "1/3", "1/4", "1/5"],
        correctAnswer: "1/4",
        explanation: "You ate 1 piece out of 4 equal pieces, which is 1/4 (one-fourth).",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In the fraction 3/4, the number 3 is called the numerator.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "The top number in a fraction is called the numerator. The bottom number is the denominator.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which fraction is larger: 1/2 or 1/4?",
        options: ["1/2", "1/4", "They are equal"],
        correctAnswer: "1/2",
        explanation: "1/2 is larger because when you divide something into fewer pieces, each piece is bigger!",
        points: 10,
      },
      {
        id: "q4",
        type: "fill_blank",
        question: "If you have 2/4 of a pie, that's the same as having ___ (write as a fraction like 1/2)",
        correctAnswer: "1/2",
        explanation: "2/4 = 1/2. These are equivalent fractions!",
        points: 15,
      },
    ],
  },

  // Science - Solar System
  "3-solar-system": {
    id: "3-solar-system-quiz",
    title: "Solar System Quiz",
    instructions: "Answer questions about our solar system!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is at the center of our solar system?",
        options: ["Earth", "Moon", "Sun", "Mars"],
        correctAnswer: "Sun",
        explanation: "The Sun is a star at the center of our solar system. All planets orbit around it.",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these planets in order from closest to the Sun to farthest:",
        options: ["Earth", "Mars", "Venus", "Mercury"],
        correctAnswer: ["Mercury", "Venus", "Earth", "Mars"],
        explanation: "The order from the Sun is: Mercury, Venus, Earth, Mars (the inner rocky planets).",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Earth is the only planet in our solar system with a moon.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Many planets have moons! Mars has 2, Jupiter has at least 95, and Saturn has over 140!",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "Which planet is known as the 'Red Planet'?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        explanation: "Mars is called the Red Planet because of the iron oxide (rust) on its surface.",
        points: 10,
      },
    ],
  },

  // Science - Atoms
  "7-atoms": {
    id: "7-atoms-quiz",
    title: "Atomic Structure Quiz",
    instructions: "Test your knowledge of atoms and their structure!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What are the three main particles that make up an atom?",
        options: [
          "Protons, neutrons, and electrons",
          "Protons, neurons, and electrons",
          "Positrons, neutrons, and electrons",
          "Protons, neutrons, and positrons",
        ],
        correctAnswer: "Protons, neutrons, and electrons",
        explanation: "Atoms consist of protons (positive), neutrons (neutral), and electrons (negative).",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each particle to its charge:",
        options: ["Proton", "Neutron", "Electron"],
        matchTargets: ["Positive (+)", "Neutral (0)", "Negative (-)"],
        correctAnswer: ["Positive (+)", "Neutral (0)", "Negative (-)"],
        explanation: "Protons are positive, neutrons have no charge, and electrons are negative.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Electrons orbit the nucleus of an atom.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Electrons move around the nucleus in regions called electron shells or orbitals.",
        points: 10,
      },
      {
        id: "q4",
        type: "fill_blank",
        question: "The center of an atom is called the ___.",
        correctAnswer: "nucleus",
        explanation: "The nucleus is the central core of an atom, containing protons and neutrons.",
        points: 10,
      },
      {
        id: "q5",
        type: "multiple_choice",
        question: "What determines the element of an atom?",
        options: [
          "Number of electrons",
          "Number of neutrons",
          "Number of protons",
          "Size of the nucleus",
        ],
        correctAnswer: "Number of protons",
        explanation: "The atomic number (number of protons) determines what element an atom is.",
        points: 15,
      },
    ],
  },
};

/**
 * Get quiz configuration for a lesson
 */
export function getQuizForLesson(lessonId: string): QuizConfig | null {
  return quizConfigs[lessonId] ?? null;
}

/**
 * Check if a lesson has a quiz
 */
export function hasQuiz(lessonId: string): boolean {
  return lessonId in quizConfigs;
}

/**
 * Get all available quiz IDs
 */
export function getAllQuizIds(): string[] {
  return Object.keys(quizConfigs);
}
