/**
 * Quiz Data
 * Sample quiz configurations for curriculum lessons
 */

import type { QuizConfig } from "./types";

/**
 * Quiz configurations mapped by lesson ID
 */
export const quizConfigs: Record<string, QuizConfig> = {
  // Kindergarten Math - Counting
  "k-count-1-10": {
    id: "k-count-1-10-quiz",
    title: "Counting 1 to 10 Quiz",
    instructions: "Answer these questions about counting from 1 to 10.",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many apples are in this picture? 🍎🍎🍎",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3",
        explanation: "Count each apple: 1, 2, 3. There are 3 apples!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What number comes after 5?",
        options: ["4", "5", "6", "7"],
        correctAnswer: "6",
        explanation: "After 5 comes 6. The sequence is: 5, 6, 7...",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The number 8 is bigger than the number 6.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 8 is bigger than 6 because it comes after 6 when counting.",
        points: 10,
      },
      {
        id: "q4",
        type: "ordering",
        question: "Put these numbers in order from smallest to biggest:",
        options: ["3", "1", "5", "2", "4"],
        correctAnswer: ["1", "2", "3", "4", "5"],
        explanation: "The correct order is: 1, 2, 3, 4, 5",
        points: 20,
      },
    ],
  },

  // Kindergarten Math - 2D Shapes
  "k-2d-shapes": {
    id: "k-2d-shapes-quiz",
    title: "2D Shapes Quiz",
    instructions: "Let's see what you learned about shapes!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many sides does a triangle have?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3",
        explanation: "A triangle has 3 sides. Tri means three!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each shape to its number of sides:",
        options: ["Circle", "Triangle", "Square", "Rectangle"],
        matchTargets: ["0 sides", "3 sides", "4 sides", "4 sides"],
        correctAnswer: ["0 sides", "3 sides", "4 sides", "4 sides"],
        explanation: "Circles have no straight sides, triangles have 3, and both squares and rectangles have 4 sides.",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A circle has corners.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "A circle is round and has no corners at all!",
        points: 10,
      },
    ],
  },

  // Kindergarten Math - 3D Shapes
  "k-3d-shapes": {
    id: "k-3d-shapes-quiz",
    title: "3D Shapes Quiz",
    instructions: "Test your knowledge of 3D shapes!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which shape looks like a ball?",
        options: ["Cube", "Sphere", "Cylinder", "Cone"],
        correctAnswer: "Sphere",
        explanation: "A sphere is round like a ball!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "A box is shaped like a:",
        options: ["Sphere", "Cone", "Cube", "Cylinder"],
        correctAnswer: "Cube",
        explanation: "A cube has 6 flat faces, just like a box!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A cone has a flat bottom and a point at the top.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Think of an ice cream cone - flat on bottom, pointy on top.",
        points: 10,
      },
    ],
  },

  // Kindergarten Math - Counting 11-20
  "k-count-11-20": {
    id: "k-count-11-20-quiz",
    title: "Counting 11 to 20 Quiz",
    instructions: "Let's count bigger numbers! 🔢",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What number comes after 10?",
        options: ["9", "10", "11", "12"],
        correctAnswer: "11",
        explanation: "After 10 comes 11. Keep counting!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "How many stars? ⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐",
        options: ["13", "14", "15", "16"],
        correctAnswer: "15",
        explanation: "Count each star: there are 15 stars!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The number 18 comes before 17.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "18 comes AFTER 17, not before!",
        points: 10,
      },
      {
        id: "q4",
        type: "ordering",
        question: "Put these numbers in order from smallest to biggest:",
        options: ["15", "12", "18", "11"],
        correctAnswer: ["11", "12", "15", "18"],
        explanation: "The correct order is: 11, 12, 15, 18",
        points: 20,
      },
    ],
  },

  // Kindergarten Math - Addition Introduction
  "k-addition-intro": {
    id: "k-addition-intro-quiz",
    title: "Introduction to Addition Quiz",
    instructions: "Let's practice adding! ➕",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "🍎🍎 + 🍎 = How many apples?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3",
        explanation: "2 apples plus 1 apple equals 3 apples!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "1 + 1 = ___",
        correctAnswer: "2",
        explanation: "1 plus 1 equals 2!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "2 + 2 = ?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "4",
        explanation: "2 plus 2 equals 4!",
        points: 10,
      },
      {
        id: "q4",
        type: "true_false",
        question: "When we add, we put things together.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Adding means putting things together to get more.",
        points: 10,
      },
    ],
  },

  // Kindergarten Math - Subtraction Introduction
  "k-subtraction-intro": {
    id: "k-subtraction-intro-quiz",
    title: "Introduction to Subtraction Quiz",
    instructions: "Let's practice taking away! ➖",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "You have 3 cookies 🍪🍪🍪. You eat 1. How many are left?",
        options: ["1", "2", "3", "4"],
        correctAnswer: "2",
        explanation: "3 cookies minus 1 cookie equals 2 cookies!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "4 - 1 = ___",
        correctAnswer: "3",
        explanation: "4 minus 1 equals 3!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "When we subtract, we take things away.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Subtracting means taking away to get less.",
        points: 10,
      },
    ],
  },

  // Kindergarten Reading - Alphabet
  "k-alphabet": {
    id: "k-alphabet-quiz",
    title: "The Alphabet Quiz",
    instructions: "Let's test what you know about letters! 🔤",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What letter comes after A?",
        options: ["C", "B", "D", "Z"],
        correctAnswer: "B",
        explanation: "A, B, C! B comes after A.",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these letters in ABC order:",
        options: ["C", "A", "D", "B"],
        correctAnswer: ["A", "B", "C", "D"],
        explanation: "The alphabet goes: A, B, C, D!",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The letter Z is the last letter of the alphabet.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The alphabet ends with Z.",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "How many letters are in the alphabet?",
        options: ["20", "24", "26", "30"],
        correctAnswer: "26",
        explanation: "There are 26 letters from A to Z!",
        points: 10,
      },
    ],
  },

  // Kindergarten Reading - Letter Sounds
  "k-letter-sounds": {
    id: "k-letter-sounds-quiz",
    title: "Letter Sounds Quiz",
    instructions: "Match letters with their sounds! 🔊",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What sound does the letter S make?",
        options: ["sss (like a snake)", "mmm", "bbb", "rrr"],
        correctAnswer: "sss (like a snake)",
        explanation: "S makes the 'sss' sound, like a snake!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which letter makes the 'mmmm' sound?",
        options: ["N", "M", "B", "P"],
        correctAnswer: "M",
        explanation: "M makes the 'mmmm' sound!",
        points: 10,
      },
      {
        id: "q3",
        type: "matching",
        question: "Match each letter to its sound:",
        options: ["B", "C", "D"],
        matchTargets: ["buh", "kuh", "duh"],
        correctAnswer: ["buh", "kuh", "duh"],
        explanation: "B says 'buh', C says 'kuh', D says 'duh'!",
        points: 15,
      },
    ],
  },

  // Kindergarten Reading - Rhyming
  "k-rhyming": {
    id: "k-rhyming-quiz",
    title: "Rhyming Words Quiz",
    instructions: "Find words that sound alike at the end! 🎵",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which word rhymes with CAT?",
        options: ["Dog", "Hat", "Cup", "Run"],
        correctAnswer: "Hat",
        explanation: "Cat and Hat both end with 'at' - they rhyme!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which word rhymes with SUN?",
        options: ["Moon", "Fun", "Star", "Hot"],
        correctAnswer: "Fun",
        explanation: "Sun and Fun both end with 'un' - they rhyme!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Dog and Frog rhyme.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Dog and Frog both end with 'og'.",
        points: 10,
      },
    ],
  },

  // Kindergarten Science - Weather Types
  "k-weather-types": {
    id: "k-weather-types-quiz",
    title: "Types of Weather Quiz",
    instructions: "What do you know about weather? ☀️🌧️",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What do we call it when water falls from the sky?",
        options: ["Sunny", "Rain", "Wind", "Snow"],
        correctAnswer: "Rain",
        explanation: "When water drops fall from clouds, it's called rain!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match the weather to its picture:",
        options: ["☀️", "🌧️", "❄️"],
        matchTargets: ["Sunny", "Rainy", "Snowy"],
        correctAnswer: ["Sunny", "Rainy", "Snowy"],
        explanation: "Sun means sunny, raindrops mean rainy, snowflake means snowy!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Clouds can be in the sky on sunny days.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! We can have sun and some clouds at the same time.",
        points: 10,
      },
    ],
  },

  // Kindergarten Science - Seasons
  "k-seasons": {
    id: "k-seasons-quiz",
    title: "Seasons Quiz",
    instructions: "Learn about the four seasons! 🌸☀️🍂❄️",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In which season do leaves fall from trees?",
        options: ["Spring", "Summer", "Fall", "Winter"],
        correctAnswer: "Fall",
        explanation: "In fall (autumn), leaves change color and fall from trees!",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put the seasons in order, starting with Spring:",
        options: ["Winter", "Fall", "Summer", "Spring"],
        correctAnswer: ["Spring", "Summer", "Fall", "Winter"],
        explanation: "The seasons go: Spring, Summer, Fall, Winter!",
        points: 20,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which season is the coldest?",
        options: ["Spring", "Summer", "Fall", "Winter"],
        correctAnswer: "Winter",
        explanation: "Winter is the coldest season with snow in many places!",
        points: 10,
      },
    ],
  },

  // Kindergarten Science - Living vs Non-Living
  "k-living-nonliving": {
    id: "k-living-nonliving-quiz",
    title: "Living vs Non-Living Quiz",
    instructions: "Can you tell what's alive? 🌱🪨",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which one is a living thing?",
        options: ["Rock", "Tree", "Car", "Table"],
        correctAnswer: "Tree",
        explanation: "Trees are living! They grow, need water, and make seeds.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A dog is a living thing.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Dogs are alive - they eat, breathe, grow, and move!",
        points: 10,
      },
      {
        id: "q3",
        type: "matching",
        question: "Is it living or non-living?",
        options: ["Cat", "Flower", "Rock"],
        matchTargets: ["Living", "Living", "Non-living"],
        correctAnswer: ["Living", "Living", "Non-living"],
        explanation: "Cats and flowers are living. Rocks are non-living!",
        points: 15,
      },
    ],
  },

  // Kindergarten History - Community Helpers
  "k-helpers": {
    id: "k-helpers-quiz",
    title: "Community Helpers Quiz",
    instructions: "Who helps in our community? 👨‍🚒👩‍⚕️",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Who helps put out fires?",
        options: ["Teacher", "Doctor", "Firefighter", "Chef"],
        correctAnswer: "Firefighter",
        explanation: "Firefighters are brave helpers who put out fires!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each helper to what they do:",
        options: ["Doctor", "Teacher", "Police Officer"],
        matchTargets: ["Helps sick people", "Helps us learn", "Keeps us safe"],
        correctAnswer: ["Helps sick people", "Helps us learn", "Keeps us safe"],
        explanation: "Doctors help sick people, teachers help us learn, police keep us safe!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Librarians help us find books.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Librarians are helpers who work with books!",
        points: 10,
      },
    ],
  },

  // Kindergarten Technology - Parts of Computer
  "k-parts-computer": {
    id: "k-parts-computer-quiz",
    title: "Parts of a Computer Quiz",
    instructions: "What are the parts of a computer? 💻",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What part of the computer shows pictures and words?",
        options: ["Mouse", "Keyboard", "Screen/Monitor", "Printer"],
        correctAnswer: "Screen/Monitor",
        explanation: "The screen (or monitor) shows us pictures and words!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What do we use to type letters?",
        options: ["Mouse", "Keyboard", "Screen", "Speaker"],
        correctAnswer: "Keyboard",
        explanation: "We type letters and numbers on the keyboard!",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A mouse helps us click and point on the screen.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! We use the mouse to move the pointer and click!",
        points: 10,
      },
    ],
  },

  // Grade 1 Math - Tens and Ones
  "1-tens-ones": {
    id: "1-tens-ones-quiz",
    title: "Tens and Ones Quiz",
    instructions: "Let's learn about place value!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In the number 25, how many tens are there?",
        options: ["2", "5", "25", "7"],
        correctAnswer: "2",
        explanation: "25 has 2 tens (20) and 5 ones (5). 20 + 5 = 25!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The number 34 has 3 tens and ___ ones.",
        correctAnswer: "4",
        explanation: "34 = 30 + 4, so there are 4 ones!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What number has 4 tens and 7 ones?",
        options: ["47", "74", "11", "41"],
        correctAnswer: "47",
        explanation: "4 tens = 40, plus 7 ones = 47!",
        points: 10,
      },
      {
        id: "q4",
        type: "true_false",
        question: "The number 50 has 5 tens and 0 ones.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 50 = 5 tens (50) + 0 ones.",
        points: 10,
      },
    ],
  },

  // Grade 1 Math - Addition within 20
  "1-add-within-20": {
    id: "1-add-within-20-quiz",
    title: "Addition within 20 Quiz",
    instructions: "Practice adding numbers up to 20!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "fill_blank",
        question: "8 + 5 = ___",
        correctAnswer: "13",
        explanation: "8 + 5 = 13. You can count on: 8... 9, 10, 11, 12, 13!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What is 9 + 7?",
        options: ["14", "15", "16", "17"],
        correctAnswer: "16",
        explanation: "9 + 7 = 16. Think: 9 + 1 = 10, then 10 + 6 = 16!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which addition equals 15?",
        options: ["6 + 8", "7 + 8", "9 + 5", "8 + 8"],
        correctAnswer: "7 + 8",
        explanation: "7 + 8 = 15!",
        points: 15,
      },
    ],
  },

  // Grade 1 Reading - Short Vowels
  "1-short-vowels": {
    id: "1-short-vowels-quiz",
    title: "Short Vowels Quiz",
    instructions: "Listen for short vowel sounds!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which word has a short 'a' sound?",
        options: ["cake", "cat", "car", "cape"],
        correctAnswer: "cat",
        explanation: "Cat has the short 'a' sound like in 'apple'!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match words with the same short vowel sound:",
        options: ["bed", "pig", "hot"],
        matchTargets: ["short e", "short i", "short o"],
        correctAnswer: ["short e", "short i", "short o"],
        explanation: "Bed has short e, pig has short i, hot has short o!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The word 'cup' has a short 'u' sound.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Cup has the short 'u' sound like in 'umbrella'.",
        points: 10,
      },
    ],
  },

  // Grade 1 Science - Light Sources
  "1-light-sources": {
    id: "1-light-sources-quiz",
    title: "Light Sources Quiz",
    instructions: "Where does light come from?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the biggest source of light for Earth?",
        options: ["Moon", "Stars", "Sun", "Lamp"],
        correctAnswer: "Sun",
        explanation: "The Sun is our biggest and brightest source of light!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A flashlight makes its own light.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! A flashlight is a light source - it makes light!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which is NOT a light source?",
        options: ["Candle", "Mirror", "Lamp", "Fire"],
        correctAnswer: "Mirror",
        explanation: "A mirror reflects light but doesn't make its own light.",
        points: 15,
      },
    ],
  },

  // Grade 1 Science - Day and Night
  "1-day-night": {
    id: "1-day-night-quiz",
    title: "Day and Night Quiz",
    instructions: "Why do we have day and night?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What makes daytime bright?",
        options: ["Moon", "Sun", "Stars", "Clouds"],
        correctAnswer: "Sun",
        explanation: "The Sun shines on Earth and makes daytime bright!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Earth spins around, which causes day and night.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! As Earth spins, different parts face the Sun.",
        points: 10,
      },
      {
        id: "q3",
        type: "ordering",
        question: "Put these in order from morning to night:",
        options: ["Sunset", "Sunrise", "Noon", "Midnight"],
        correctAnswer: ["Sunrise", "Noon", "Sunset", "Midnight"],
        explanation: "A day goes: sunrise, noon, sunset, midnight!",
        points: 20,
      },
    ],
  },

  // Grade 1 History - Rules and Laws
  "1-rules-laws": {
    id: "1-rules-laws-quiz",
    title: "Rules and Laws Quiz",
    instructions: "Why do we have rules?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Why do we have rules?",
        options: ["To have fun", "To keep us safe", "To make us sad", "To waste time"],
        correctAnswer: "To keep us safe",
        explanation: "Rules help keep everyone safe and things fair!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "It's a rule to raise your hand before speaking in class.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! This rule helps everyone get a turn to speak.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is a law?",
        options: ["A game", "A rule made by the government", "A toy", "A book"],
        correctAnswer: "A rule made by the government",
        explanation: "Laws are rules that everyone in a community must follow.",
        points: 15,
      },
    ],
  },

  // Grade 1 Technology - Internet Safety
  "1-internet-safety": {
    id: "1-internet-safety-quiz",
    title: "Internet Safety Quiz",
    instructions: "Stay safe online! 🔒",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Should you share your password with friends?",
        options: ["Yes, always", "No, never", "Only best friends", "Only online"],
        correctAnswer: "No, never",
        explanation: "Passwords are secret! Only share with parents.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "You should tell a grown-up if something online makes you feel scared or sad.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Always tell a trusted adult if something online upsets you.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What should you NOT share online?",
        options: ["Your favorite color", "Your full name and address", "Your favorite animal", "Your hobby"],
        correctAnswer: "Your full name and address",
        explanation: "Never share personal info like your full name, address, or school online!",
        points: 15,
      },
    ],
  },

  // Grade 2 Math - Understanding Hundreds
  "2-hundreds": {
    id: "2-hundreds-quiz",
    title: "Understanding Hundreds Quiz",
    instructions: "Learn about hundreds place value!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How many tens are in 100?",
        options: ["1", "10", "100", "0"],
        correctAnswer: "10",
        explanation: "100 = 10 tens. Each ten has 10 ones!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The number 352 has ___ hundreds.",
        correctAnswer: "3",
        explanation: "352 has 3 hundreds (300) + 5 tens (50) + 2 ones (2).",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What number has 4 hundreds, 2 tens, and 5 ones?",
        options: ["245", "425", "524", "452"],
        correctAnswer: "425",
        explanation: "4 hundreds (400) + 2 tens (20) + 5 ones (5) = 425!",
        points: 15,
      },
    ],
  },

  // Grade 2 Math - Telling Time
  "2-time": {
    id: "2-time-quiz",
    title: "Telling Time Quiz",
    instructions: "Can you read the clock? ⏰",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If the hour hand points to 3 and the minute hand points to 12, what time is it?",
        options: ["12:03", "3:00", "3:12", "12:00"],
        correctAnswer: "3:00",
        explanation: "When the minute hand is on 12, it's exactly that hour - 3:00!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "The short hand on a clock shows the hours.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The short hand shows hours, long hand shows minutes.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "There are ___ minutes in one hour.",
        correctAnswer: "60",
        explanation: "One hour has 60 minutes!",
        points: 10,
      },
    ],
  },

  // Grade 2 Reading - Character Analysis
  "2-character-analysis": {
    id: "2-character-analysis-quiz",
    title: "Character Analysis Quiz",
    instructions: "Learn about story characters!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a character in a story?",
        options: ["The title", "A person or animal in the story", "The setting", "The ending"],
        correctAnswer: "A person or animal in the story",
        explanation: "Characters are the people, animals, or creatures in a story!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "We can learn about a character by what they say and do.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! A character's words and actions tell us about them.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If a character shares their toys, they are probably:",
        options: ["Mean", "Selfish", "Kind", "Scary"],
        correctAnswer: "Kind",
        explanation: "Sharing shows the character is kind and caring!",
        points: 15,
      },
    ],
  },

  // Grade 2 Science - Habitats
  "2-habitats": {
    id: "2-habitats-quiz",
    title: "Habitats Quiz",
    instructions: "Where do animals live? 🏠🌲",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a habitat?",
        options: ["A type of food", "A place where animals live", "A kind of weather", "An animal's name"],
        correctAnswer: "A place where animals live",
        explanation: "A habitat is a place where plants and animals live and find what they need!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each animal to its habitat:",
        options: ["Fish", "Camel", "Polar Bear"],
        matchTargets: ["Ocean", "Desert", "Arctic"],
        correctAnswer: ["Ocean", "Desert", "Arctic"],
        explanation: "Fish live in water, camels in deserts, polar bears in the Arctic!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Animals need food, water, and shelter from their habitat.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Habitats provide everything animals need to survive.",
        points: 10,
      },
    ],
  },

  // Grade 2 Science - Food Chains
  "2-food-chains": {
    id: "2-food-chains-quiz",
    title: "Food Chains Quiz",
    instructions: "How do living things get energy? 🌱🐛🐦",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put this food chain in order:",
        options: ["Bird", "Sun", "Caterpillar", "Leaf"],
        correctAnswer: ["Sun", "Leaf", "Caterpillar", "Bird"],
        explanation: "Sun → Leaf → Caterpillar → Bird. Energy flows from sun to plants to animals!",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Where does a food chain start?",
        options: ["Animals", "The Sun", "Humans", "Water"],
        correctAnswer: "The Sun",
        explanation: "All food chains start with the Sun! Plants use sunlight to make food.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Plants are called producers because they make their own food.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Plants produce food using sunlight, water, and air.",
        points: 10,
      },
    ],
  },

  // Grade 2 History - Wants and Needs
  "2-wants-needs": {
    id: "2-wants-needs-quiz",
    title: "Wants and Needs Quiz",
    instructions: "What do we need vs. what do we want?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which is a NEED?",
        options: ["Video games", "Food", "Toys", "Candy"],
        correctAnswer: "Food",
        explanation: "Food is a need - we must have it to live! Toys are wants.",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Is it a want or a need?",
        options: ["Water", "Shelter", "New bike"],
        matchTargets: ["Need", "Need", "Want"],
        correctAnswer: ["Need", "Need", "Want"],
        explanation: "Water and shelter are needs. A new bike is a want!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "We can live without our wants, but not without our needs.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Correct! Needs are for survival. Wants make life more fun!",
        points: 10,
      },
    ],
  },

  // Grade 2 Technology - Sequences
  "2-sequences": {
    id: "2-sequences-quiz",
    title: "Sequences Quiz",
    instructions: "Put steps in the right order! 📝",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put these steps for making a sandwich in order:",
        options: ["Add filling", "Put bread on top", "Get two slices of bread", "Eat the sandwich"],
        correctAnswer: ["Get two slices of bread", "Add filling", "Put bread on top", "Eat the sandwich"],
        explanation: "First get bread, add filling, close it, then eat!",
        points: 20,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In a sequence, order matters.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Sequences are steps that must be done in a specific order.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What comes first when brushing your teeth?",
        options: ["Rinse your mouth", "Put toothpaste on brush", "Brush your teeth", "Put away the brush"],
        correctAnswer: "Put toothpaste on brush",
        explanation: "First put toothpaste on, then brush, then rinse!",
        points: 10,
      },
    ],
  },

  // Grade 3 - Multiplication Introduction
  "3-mult-intro": {
    id: "3-mult-intro-quiz",
    title: "Introduction to Multiplication Quiz",
    instructions: "Show what you learned about multiplication!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 3 × 4?",
        options: ["7", "10", "12", "14"],
        correctAnswer: "12",
        explanation: "3 × 4 means 3 groups of 4, which equals 12.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "5 × 2 = ___",
        correctAnswer: "10",
        explanation: "5 × 2 = 10. Think of it as 5 + 5!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If you have 4 bags with 3 apples in each bag, how many apples do you have in total?",
        options: ["7", "10", "12", "15"],
        correctAnswer: "12",
        explanation: "4 bags × 3 apples = 12 apples total.",
        points: 15,
      },
      {
        id: "q4",
        type: "true_false",
        question: "2 × 6 gives the same answer as 6 × 2.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! This is called the commutative property. Order doesn't matter in multiplication.",
        points: 10,
      },
      {
        id: "q5",
        type: "ordering",
        question: "Put these products in order from smallest to largest:",
        options: ["2×5", "3×3", "4×2", "1×6"],
        correctAnswer: ["1×6", "4×2", "3×3", "2×5"],
        explanation: "1×6=6, 4×2=8, 3×3=9, 2×5=10. So the order is: 6, 8, 9, 10.",
        points: 15,
      },
    ],
  },

  // Grade 3 - Fractions Introduction
  "3-fractions-intro": {
    id: "3-fractions-intro-quiz",
    title: "Introduction to Fractions Quiz",
    instructions: "Test your understanding of fractions!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If a pizza is cut into 4 equal pieces and you eat 1 piece, what fraction did you eat?",
        options: ["1/2", "1/3", "1/4", "1/5"],
        correctAnswer: "1/4",
        explanation: "You ate 1 piece out of 4 equal pieces, which is 1/4 (one-fourth).",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In the fraction 3/4, the number 3 is called the numerator.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "The top number in a fraction is called the numerator. The bottom number is the denominator.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which fraction is larger: 1/2 or 1/4?",
        options: ["1/2", "1/4", "They are equal"],
        correctAnswer: "1/2",
        explanation: "1/2 is larger because when you divide something into fewer pieces, each piece is bigger!",
        points: 10,
      },
      {
        id: "q4",
        type: "fill_blank",
        question: "If you have 2/4 of a pie, that's the same as having ___ (write as a fraction like 1/2)",
        correctAnswer: "1/2",
        explanation: "2/4 = 1/2. These are equivalent fractions!",
        points: 15,
      },
    ],
  },

  // Science - Solar System
  "3-solar-system": {
    id: "3-solar-system-quiz",
    title: "Solar System Quiz",
    instructions: "Answer questions about our solar system!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is at the center of our solar system?",
        options: ["Earth", "Moon", "Sun", "Mars"],
        correctAnswer: "Sun",
        explanation: "The Sun is a star at the center of our solar system. All planets orbit around it.",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these planets in order from closest to the Sun to farthest:",
        options: ["Earth", "Mars", "Venus", "Mercury"],
        correctAnswer: ["Mercury", "Venus", "Earth", "Mars"],
        explanation: "The order from the Sun is: Mercury, Venus, Earth, Mars (the inner rocky planets).",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Earth is the only planet in our solar system with a moon.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Many planets have moons! Mars has 2, Jupiter has at least 95, and Saturn has over 140!",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "Which planet is known as the 'Red Planet'?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        explanation: "Mars is called the Red Planet because of the iron oxide (rust) on its surface.",
        points: 10,
      },
    ],
  },

  // ============================================================================
  // GRADE 3 QUIZZES
  // ============================================================================

  // Grade 3 Math - Multiplication Facts
  "3-mult-facts": {
    id: "3-mult-facts-quiz",
    title: "Multiplication Facts Quiz",
    instructions: "Practice your multiplication facts!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "fill_blank",
        question: "7 × 8 = ___",
        correctAnswer: "56",
        explanation: "7 × 8 = 56. This is one of the trickier facts to memorize!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What is 9 × 6?",
        options: ["45", "54", "56", "63"],
        correctAnswer: "54",
        explanation: "9 × 6 = 54. A trick: 9 × 6 = 54 (5 + 4 = 9).",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "6 × 7 = ___",
        correctAnswer: "42",
        explanation: "6 × 7 = 42. Remember: 6, 7, 8... 6 × 7 = 42!",
        points: 10,
      },
      {
        id: "q4",
        type: "matching",
        question: "Match each multiplication to its product:",
        options: ["8 × 8", "9 × 9", "7 × 7", "6 × 6"],
        matchTargets: ["64", "81", "49", "36"],
        correctAnswer: ["64", "81", "49", "36"],
        explanation: "These are all perfect squares!",
        points: 20,
      },
    ],
  },

  // Grade 3 Math - Division Introduction
  "3-division-intro": {
    id: "3-division-intro-quiz",
    title: "Introduction to Division Quiz",
    instructions: "Show what you know about division!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "12 ÷ 3 = ?",
        options: ["3", "4", "5", "6"],
        correctAnswer: "4",
        explanation: "12 ÷ 3 = 4. Think: how many groups of 3 make 12?",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "20 ÷ 4 = ___",
        correctAnswer: "5",
        explanation: "20 ÷ 4 = 5. You can share 20 items equally among 4 people.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Division is the opposite of multiplication.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Division and multiplication are inverse operations.",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "If you have 24 cookies and want to share them equally among 6 friends, how many cookies does each friend get?",
        options: ["3", "4", "5", "6"],
        correctAnswer: "4",
        explanation: "24 ÷ 6 = 4 cookies per friend.",
        points: 15,
      },
    ],
  },

  // Grade 3 Reading - Theme
  "3-theme": {
    id: "3-theme-quiz",
    title: "Finding the Theme Quiz",
    instructions: "Answer questions about story themes!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the theme of a story?",
        options: ["The main character", "The setting", "The main message or lesson", "The plot"],
        correctAnswer: "The main message or lesson",
        explanation: "The theme is the big idea or lesson the author wants you to learn.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "In a story where a character keeps trying until they succeed, what might the theme be?",
        options: ["Give up when things get hard", "Never give up", "Always ask for help", "Stay inside"],
        correctAnswer: "Never give up",
        explanation: "When a character perseveres, the theme is often about not giving up.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A story can only have one theme.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Stories can have multiple themes or messages!",
        points: 10,
      },
    ],
  },

  // Grade 3 Reading - Point of View
  "3-point-of-view": {
    id: "3-point-of-view-quiz",
    title: "Point of View Quiz",
    instructions: "Identify different points of view!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If a story uses 'I' and 'me,' what point of view is it?",
        options: ["First person", "Second person", "Third person"],
        correctAnswer: "First person",
        explanation: "First person uses 'I,' 'me,' 'my' - the narrator is in the story.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "If a story uses 'he,' 'she,' and 'they,' what point of view is it?",
        options: ["First person", "Second person", "Third person"],
        correctAnswer: "Third person",
        explanation: "Third person uses 'he,' 'she,' 'they' - an outside narrator tells the story.",
        points: 10,
      },
      {
        id: "q3",
        type: "matching",
        question: "Match the pronoun to the point of view:",
        options: ["I went to school", "She went to school", "You went to school"],
        matchTargets: ["First person", "Third person", "Second person"],
        correctAnswer: ["First person", "Third person", "Second person"],
        explanation: "I = first, she/he = third, you = second person.",
        points: 15,
      },
    ],
  },

  // Grade 3 Science - Forces & Friction
  "3-friction": {
    id: "3-friction-quiz",
    title: "Friction Quiz",
    instructions: "Test your knowledge about friction!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is friction?",
        options: ["A force that speeds things up", "A force that slows things down", "A type of energy", "A kind of motion"],
        correctAnswer: "A force that slows things down",
        explanation: "Friction is a force that opposes motion and slows things down.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which surface would have MORE friction?",
        options: ["Ice", "Sandpaper", "Glass", "Wet floor"],
        correctAnswer: "Sandpaper",
        explanation: "Rough surfaces like sandpaper create more friction than smooth surfaces.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Friction can produce heat.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Rub your hands together - the friction creates heat!",
        points: 10,
      },
    ],
  },

  // Grade 3 Science - Magnets
  "3-magnets": {
    id: "3-magnets-quiz",
    title: "Magnets Quiz",
    instructions: "What do you know about magnets?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What do we call the ends of a magnet?",
        options: ["Sides", "Poles", "Points", "Edges"],
        correctAnswer: "Poles",
        explanation: "Magnets have two poles: North and South.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Two north poles will attract each other.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Like poles repel! North-North or South-South push apart. Opposite poles attract.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which material would a magnet attract?",
        options: ["Wood", "Plastic", "Iron", "Glass"],
        correctAnswer: "Iron",
        explanation: "Magnets attract metals like iron, nickel, and cobalt.",
        points: 10,
      },
      {
        id: "q4",
        type: "matching",
        question: "Match the poles to what happens:",
        options: ["North + South", "North + North", "South + South"],
        matchTargets: ["Attract", "Repel", "Repel"],
        correctAnswer: ["Attract", "Repel", "Repel"],
        explanation: "Opposite poles attract, same poles repel!",
        points: 15,
      },
    ],
  },

  // Grade 3 Science - Life Cycles
  "3-plant-life-cycle": {
    id: "3-plant-life-cycle-quiz",
    title: "Plant Life Cycle Quiz",
    instructions: "Show what you know about how plants grow!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put the plant life cycle in order:",
        options: ["Adult plant", "Seed", "Seedling", "Flowering"],
        correctAnswer: ["Seed", "Seedling", "Adult plant", "Flowering"],
        explanation: "Seed → Seedling → Adult plant → Flowering (then back to seeds!)",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What do seeds need to germinate (start growing)?",
        options: ["Only sunlight", "Water, warmth, and air", "Only soil", "Only water"],
        correctAnswer: "Water, warmth, and air",
        explanation: "Seeds need water, warmth, and air to germinate.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "All plants produce flowers.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Not all plants flower! Ferns and mosses reproduce differently.",
        points: 10,
      },
    ],
  },

  // Grade 3 History - Local Government
  "3-local-gov": {
    id: "3-local-gov-quiz",
    title: "Local Government Quiz",
    instructions: "What do you know about your local government?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Who is usually the leader of a city?",
        options: ["President", "Governor", "Mayor", "Senator"],
        correctAnswer: "Mayor",
        explanation: "A mayor is the elected leader of a city or town.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Local government takes care of things like parks and libraries.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Local governments run parks, libraries, fire departments, and more.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is one way citizens can participate in local government?",
        options: ["Voting", "Moving away", "Ignoring laws", "Staying home"],
        correctAnswer: "Voting",
        explanation: "Voting is an important way to participate in democracy!",
        points: 10,
      },
    ],
  },

  // Grade 3 Technology - Block Coding
  "3-block-coding": {
    id: "3-block-coding-quiz",
    title: "Block Coding Quiz",
    instructions: "Test your coding knowledge!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is block coding?",
        options: ["Building with blocks", "Programming with drag-and-drop blocks", "Playing video games", "Drawing pictures"],
        correctAnswer: "Programming with drag-and-drop blocks",
        explanation: "Block coding uses visual blocks you snap together to write programs.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In block coding, the order of blocks matters.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The computer follows blocks in order from top to bottom.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What does a 'repeat' block do?",
        options: ["Stops the program", "Runs code multiple times", "Deletes code", "Saves the program"],
        correctAnswer: "Runs code multiple times",
        explanation: "A repeat block runs the code inside it multiple times - this is called a loop!",
        points: 10,
      },
    ],
  },

  // Grade 3 Technology - Loops
  "3-loops": {
    id: "3-loops-quiz",
    title: "Loops Quiz",
    instructions: "What do you know about loops in coding?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a loop in coding?",
        options: ["A type of bug", "Code that repeats", "A way to stop code", "A drawing tool"],
        correctAnswer: "Code that repeats",
        explanation: "A loop repeats a set of instructions multiple times.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If a loop says 'repeat 5 times,' the code inside runs ___ times.",
        correctAnswer: "5",
        explanation: "The code inside a 'repeat 5 times' loop runs exactly 5 times.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Loops help make code shorter and easier to read.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Instead of writing the same code 10 times, you use a loop.",
        points: 10,
      },
    ],
  },

  // ============================================================================
  // GRADE 4 QUIZZES
  // ============================================================================

  // Grade 4 Math - Multi-digit Multiplication
  "4-multiply-2digit": {
    id: "4-multiply-2digit-quiz",
    title: "Multi-Digit Multiplication Quiz",
    instructions: "Multiply larger numbers!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 23 × 4?",
        options: ["82", "92", "102", "112"],
        correctAnswer: "92",
        explanation: "23 × 4 = 92. Break it down: (20 × 4) + (3 × 4) = 80 + 12 = 92",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "45 × 3 = ___",
        correctAnswer: "135",
        explanation: "45 × 3 = 135. (40 × 3) + (5 × 3) = 120 + 15 = 135",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is 12 × 15?",
        options: ["150", "170", "180", "200"],
        correctAnswer: "180",
        explanation: "12 × 15 = 180. You can think: 12 × 10 = 120, 12 × 5 = 60, total = 180",
        points: 15,
      },
      {
        id: "q4",
        type: "true_false",
        question: "When multiplying by 10, you just add a zero to the end.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 24 × 10 = 240. The digits shift one place to the left.",
        points: 10,
      },
    ],
  },

  // Grade 4 Math - Fractions
  "4-equivalent-fractions": {
    id: "4-equivalent-fractions-quiz",
    title: "Equivalent Fractions Quiz",
    instructions: "Find fractions that are equal!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which fraction is equivalent to 1/2?",
        options: ["1/3", "2/4", "3/4", "1/4"],
        correctAnswer: "2/4",
        explanation: "1/2 = 2/4. Multiply both top and bottom by 2!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match equivalent fractions:",
        options: ["1/2", "1/3", "3/4"],
        matchTargets: ["2/4", "2/6", "6/8"],
        correctAnswer: ["2/4", "2/6", "6/8"],
        explanation: "Multiply or divide both parts by the same number to find equivalents.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "4/8 is equivalent to 1/2.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 4 ÷ 4 = 1 and 8 ÷ 4 = 2, so 4/8 = 1/2.",
        points: 10,
      },
    ],
  },

  // Grade 4 Math - Decimals Introduction
  "4-decimals-intro": {
    id: "4-decimals-intro-quiz",
    title: "Introduction to Decimals Quiz",
    instructions: "Learn about decimal numbers!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the decimal 0.5 equal to as a fraction?",
        options: ["1/2", "1/4", "1/5", "1/10"],
        correctAnswer: "1/2",
        explanation: "0.5 = 5/10 = 1/2 (five tenths equals one half)",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these decimals in order from smallest to largest:",
        options: ["0.7", "0.25", "0.5", "0.1"],
        correctAnswer: ["0.1", "0.25", "0.5", "0.7"],
        explanation: "0.1 < 0.25 < 0.5 < 0.7",
        points: 15,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "0.25 = ___/100 (write the numerator only)",
        correctAnswer: "25",
        explanation: "0.25 = 25/100 = 25 hundredths",
        points: 10,
      },
    ],
  },

  // Grade 4 Reading - Character Motivation
  "4-character-motivation": {
    id: "4-character-motivation-quiz",
    title: "Character Motivation Quiz",
    instructions: "Understand why characters do what they do!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is character motivation?",
        options: ["What a character looks like", "Why a character acts a certain way", "Where a character lives", "What a character says"],
        correctAnswer: "Why a character acts a certain way",
        explanation: "Motivation is the reason behind a character's actions.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "If a character studies hard because they want to become a doctor, what is their motivation?",
        options: ["Fear", "Curiosity", "A goal or dream", "Laziness"],
        correctAnswer: "A goal or dream",
        explanation: "Their dream of becoming a doctor motivates them to study.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Characters can have more than one motivation.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Characters often have multiple reasons for their actions.",
        points: 10,
      },
    ],
  },

  // Grade 4 Reading - Opinion Writing
  "4-opinion-writing": {
    id: "4-opinion-writing-quiz",
    title: "Opinion Writing Quiz",
    instructions: "Learn to express your opinions in writing!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What should opinion writing include?",
        options: ["Just your opinion", "Your opinion with reasons", "Only facts", "A story"],
        correctAnswer: "Your opinion with reasons",
        explanation: "Good opinion writing states your opinion AND supports it with reasons!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which is an opinion?",
        options: ["Dogs are mammals", "The sun rises in the east", "Pizza is the best food", "Water freezes at 32°F"],
        correctAnswer: "Pizza is the best food",
        explanation: "'Best' is a judgment - different people have different opinions!",
        points: 10,
      },
      {
        id: "q3",
        type: "ordering",
        question: "Put these parts of opinion writing in order:",
        options: ["Conclusion", "Introduction with opinion", "Reasons and examples", "Restate opinion"],
        correctAnswer: ["Introduction with opinion", "Reasons and examples", "Restate opinion", "Conclusion"],
        explanation: "Start with your opinion, give reasons, then wrap up!",
        points: 15,
      },
    ],
  },

  // Grade 4 Science - Energy Forms
  "4-energy-forms": {
    id: "4-energy-forms-quiz",
    title: "Forms of Energy Quiz",
    instructions: "Identify different types of energy!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the energy type to the example:",
        options: ["Light energy", "Sound energy", "Heat energy", "Electrical energy"],
        matchTargets: ["Sun shining", "Music playing", "Fire burning", "Lightning bolt"],
        correctAnswer: ["Sun shining", "Music playing", "Fire burning", "Lightning bolt"],
        explanation: "Energy comes in many forms and can change from one to another!",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What type of energy is stored in food?",
        options: ["Light energy", "Chemical energy", "Sound energy", "Motion energy"],
        correctAnswer: "Chemical energy",
        explanation: "Food contains chemical energy that our bodies convert to other forms.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Energy can be created from nothing.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Energy cannot be created or destroyed - it can only change forms!",
        points: 10,
      },
    ],
  },

  // Grade 4 Science - Water Cycle
  "4-water-cycle": {
    id: "4-water-cycle-quiz",
    title: "Water Cycle Quiz",
    instructions: "Learn about Earth's water cycle!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put the water cycle steps in order:",
        options: ["Precipitation", "Evaporation", "Collection", "Condensation"],
        correctAnswer: ["Evaporation", "Condensation", "Precipitation", "Collection"],
        explanation: "Water evaporates → condenses into clouds → falls as rain → collects in bodies of water",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What happens during evaporation?",
        options: ["Water falls from clouds", "Water turns to vapor and rises", "Clouds form", "Water freezes"],
        correctAnswer: "Water turns to vapor and rises",
        explanation: "Evaporation is when liquid water becomes water vapor (gas).",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "When water vapor cools and forms clouds, this is called ___.",
        correctAnswer: "condensation",
        explanation: "Condensation is when water vapor cools and turns back into tiny water droplets.",
        points: 10,
      },
    ],
  },

  // Grade 4 History - US Regions
  "4-northeast": {
    id: "4-northeast-quiz",
    title: "Northeast Region Quiz",
    instructions: "What do you know about the Northeast?",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which city in the Northeast is the largest in the United States?",
        options: ["Boston", "Philadelphia", "New York City", "Baltimore"],
        correctAnswer: "New York City",
        explanation: "New York City is the largest city in the US with over 8 million people!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "The Northeast region has all four seasons.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The Northeast experiences spring, summer, fall, and winter.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What ocean borders the Northeast region?",
        options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
        correctAnswer: "Atlantic Ocean",
        explanation: "The Atlantic Ocean is on the eastern coast of the Northeast.",
        points: 10,
      },
    ],
  },

  // Grade 4 Technology - Variables
  "4-variables": {
    id: "4-variables-quiz",
    title: "Variables in Coding Quiz",
    instructions: "Learn about variables in programming!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a variable in coding?",
        options: ["A type of loop", "A container that stores information", "A drawing tool", "A way to delete code"],
        correctAnswer: "A container that stores information",
        explanation: "Variables store data like numbers, text, or other information.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A variable can change its value during a program.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! That's why it's called a VARIable - it can vary or change.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If you have a variable called 'score' set to 10, and you add 5, what is the new value?",
        options: ["5", "10", "15", "50"],
        correctAnswer: "15",
        explanation: "10 + 5 = 15. The variable 'score' now holds 15.",
        points: 10,
      },
    ],
  },

  // Grade 4 Technology - Conditionals
  "4-conditionals": {
    id: "4-conditionals-quiz",
    title: "Conditionals Quiz",
    instructions: "Learn about if-then statements!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a conditional in coding?",
        options: ["A loop", "A decision that says 'if this, then that'", "A variable", "A comment"],
        correctAnswer: "A decision that says 'if this, then that'",
        explanation: "Conditionals let programs make decisions based on conditions.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "In 'IF it is raining THEN bring an umbrella,' what is the condition?",
        options: ["Bring an umbrella", "It is raining", "It is sunny", "Go outside"],
        correctAnswer: "It is raining",
        explanation: "The condition is what we check - 'it is raining' is being tested.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "An ELSE block runs when the IF condition is false.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! ELSE provides an alternative action when IF is not true.",
        points: 10,
      },
    ],
  },

  // ============================================================================
  // GRADE 5 QUIZZES
  // ============================================================================

  // Grade 5 Math - Fraction Operations
  "5-multiply-fractions": {
    id: "5-multiply-fractions-quiz",
    title: "Multiplying Fractions Quiz",
    instructions: "Practice multiplying fractions!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 1/2 × 1/4?",
        options: ["1/2", "1/6", "1/8", "2/4"],
        correctAnswer: "1/8",
        explanation: "Multiply numerators: 1 × 1 = 1. Multiply denominators: 2 × 4 = 8. Answer: 1/8",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "2/3 × 3/4 = ___ (write as a simplified fraction like 1/2)",
        correctAnswer: "1/2",
        explanation: "(2×3)/(3×4) = 6/12 = 1/2",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "When you multiply two fractions less than 1, the answer is smaller than either fraction.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Multiplying fractions less than 1 gives a smaller result.",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "What is 3/5 × 2/3?",
        options: ["6/15", "5/8", "2/5", "6/8"],
        correctAnswer: "2/5",
        explanation: "(3×2)/(5×3) = 6/15 = 2/5 (simplified by dividing by 3)",
        points: 15,
      },
    ],
  },

  // Grade 5 Math - Decimal Operations
  "5-multiply-decimals": {
    id: "5-multiply-decimals-quiz",
    title: "Multiplying Decimals Quiz",
    instructions: "Practice multiplying decimal numbers!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 0.5 × 0.4?",
        options: ["2.0", "0.20", "0.9", "0.02"],
        correctAnswer: "0.20",
        explanation: "5 × 4 = 20, then count 2 decimal places total = 0.20",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "1.5 × 2 = ___",
        correctAnswer: "3",
        explanation: "1.5 × 2 = 3.0 or just 3",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is 2.5 × 0.4?",
        options: ["1.0", "0.1", "10", "0.01"],
        correctAnswer: "1.0",
        explanation: "25 × 4 = 100, then count 2 decimal places = 1.00 = 1.0",
        points: 10,
      },
    ],
  },

  // Grade 5 Reading - Literary Devices
  "5-literary-devices": {
    id: "5-literary-devices-quiz",
    title: "Literary Devices Quiz",
    instructions: "Identify literary devices in writing!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the literary device to the example:",
        options: ["Simile", "Metaphor", "Personification", "Alliteration"],
        matchTargets: ["Fast as lightning", "Life is a journey", "The wind whispered", "Peter Piper picked"],
        correctAnswer: ["Fast as lightning", "Life is a journey", "The wind whispered", "Peter Piper picked"],
        explanation: "Similes use 'like' or 'as', metaphors don't, personification gives human qualities, alliteration repeats sounds.",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "'The stars danced in the night sky' is an example of:",
        options: ["Simile", "Metaphor", "Personification", "Hyperbole"],
        correctAnswer: "Personification",
        explanation: "Stars can't actually dance - giving them human actions is personification.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is hyperbole?",
        options: ["A comparison using 'like'", "Extreme exaggeration", "Repeating sounds", "A type of rhyme"],
        correctAnswer: "Extreme exaggeration",
        explanation: "Hyperbole is extreme exaggeration for effect, like 'I'm so hungry I could eat a horse.'",
        points: 10,
      },
    ],
  },

  // Grade 5 Reading - Research Skills
  "5-sources": {
    id: "5-sources-quiz",
    title: "Research Sources Quiz",
    instructions: "Learn about finding and using sources!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a primary source?",
        options: ["A textbook about history", "An encyclopedia", "A letter written during an event", "A documentary"],
        correctAnswer: "A letter written during an event",
        explanation: "Primary sources are original documents from the time being studied.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "You should always use the first website you find in your research.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "No! Always check if sources are reliable and accurate.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which is a reliable source for a research project?",
        options: ["A random blog", "Wikipedia alone", "A government website (.gov)", "Social media posts"],
        correctAnswer: "A government website (.gov)",
        explanation: "Government websites (.gov) are typically reliable and factual.",
        points: 10,
      },
    ],
  },

  // Grade 5 Science - States of Matter
  "5-states-of-matter": {
    id: "5-states-of-matter-quiz",
    title: "States of Matter Quiz",
    instructions: "Understand solids, liquids, and gases!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match each property to the correct state of matter:",
        options: ["Fixed shape and volume", "Fixed volume but takes container shape", "No fixed shape or volume"],
        matchTargets: ["Solid", "Liquid", "Gas"],
        correctAnswer: ["Solid", "Liquid", "Gas"],
        explanation: "Solids keep their shape, liquids flow, gases expand to fill containers.",
        points: 15,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What happens to particles when a solid is heated?",
        options: ["They slow down", "They move faster", "They disappear", "They multiply"],
        correctAnswer: "They move faster",
        explanation: "Adding heat gives particles more energy, making them move faster.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "When water freezes, it changes from a liquid to a ___.",
        correctAnswer: "solid",
        explanation: "Freezing is the change from liquid to solid.",
        points: 10,
      },
    ],
  },

  // Grade 5 Science - Chemical Changes
  "5-chemical-changes": {
    id: "5-chemical-changes-quiz",
    title: "Chemical Changes Quiz",
    instructions: "Learn about chemical vs physical changes!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which is an example of a chemical change?",
        options: ["Ice melting", "Wood burning", "Paper being cut", "Water evaporating"],
        correctAnswer: "Wood burning",
        explanation: "Burning creates new substances (ash, smoke) - it's irreversible!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Is it a physical or chemical change?",
        options: ["Rusting iron", "Dissolving sugar", "Baking a cake"],
        matchTargets: ["Chemical", "Physical", "Chemical"],
        correctAnswer: ["Chemical", "Physical", "Chemical"],
        explanation: "Rusting and baking create new substances. Dissolving sugar is physical - you can get it back!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Chemical changes can usually be reversed easily.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Chemical changes are typically irreversible - you can't unburn wood!",
        points: 10,
      },
    ],
  },

  // Grade 5 Science - Ecosystems
  "5-food-webs": {
    id: "5-food-webs-quiz",
    title: "Food Webs Quiz",
    instructions: "Understand how organisms are connected!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How is a food web different from a food chain?",
        options: ["It's smaller", "It shows many connected food chains", "It only includes plants", "It has no producers"],
        correctAnswer: "It shows many connected food chains",
        explanation: "Food webs show how multiple food chains connect and overlap.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "If one species disappears from a food web, it can affect many other species.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Species in a food web are interconnected, so changes ripple through.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What role do decomposers play in a food web?",
        options: ["They eat only plants", "They break down dead organisms", "They produce food", "They eat only meat"],
        correctAnswer: "They break down dead organisms",
        explanation: "Decomposers (like fungi and bacteria) break down dead matter and recycle nutrients.",
        points: 10,
      },
    ],
  },

  // Grade 5 History - Colonial Period
  "5-colonial-period": {
    id: "5-colonial-period-quiz",
    title: "Colonial America Quiz",
    instructions: "Test your knowledge of colonial times!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What was the first permanent English settlement in America?",
        options: ["Plymouth", "Jamestown", "Boston", "Philadelphia"],
        correctAnswer: "Jamestown",
        explanation: "Jamestown, Virginia was founded in 1607.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Why did the Pilgrims come to America?",
        options: ["To find gold", "For religious freedom", "To explore", "For vacation"],
        correctAnswer: "For religious freedom",
        explanation: "The Pilgrims wanted to practice their religion freely.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The 13 colonies were controlled by which country? ___",
        correctAnswer: "England",
        explanation: "The 13 colonies were British (English) colonies.",
        points: 10,
      },
    ],
  },

  // Grade 5 History - American Revolution
  "5-revolution": {
    id: "5-revolution-quiz",
    title: "American Revolution Quiz",
    instructions: "Learn about American independence!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What document declared American independence from Britain?",
        options: ["The Constitution", "The Bill of Rights", "The Declaration of Independence", "The Mayflower Compact"],
        correctAnswer: "The Declaration of Independence",
        explanation: "The Declaration of Independence was signed on July 4, 1776.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "'No taxation without representation' meant colonists wanted:",
        options: ["Lower taxes", "No government", "A say in laws that affected them", "More British soldiers"],
        correctAnswer: "A say in laws that affected them",
        explanation: "Colonists wanted representation in Parliament if they were going to be taxed.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The Boston ___ Party was a protest against British tea taxes.",
        correctAnswer: "Tea",
        explanation: "The Boston Tea Party (1773) was when colonists dumped tea into the harbor.",
        points: 10,
      },
    ],
  },

  // Grade 5 Technology - Data Visualization
  "5-data-visualization": {
    id: "5-data-visualization-quiz",
    title: "Data Visualization Quiz",
    instructions: "Learn about presenting data visually!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the chart type to its best use:",
        options: ["Bar chart", "Line graph", "Pie chart"],
        matchTargets: ["Comparing categories", "Showing change over time", "Showing parts of a whole"],
        correctAnswer: ["Comparing categories", "Showing change over time", "Showing parts of a whole"],
        explanation: "Different charts work better for different types of data!",
        points: 15,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which chart would best show how temperature changed throughout a day?",
        options: ["Pie chart", "Bar chart", "Line graph", "Table"],
        correctAnswer: "Line graph",
        explanation: "Line graphs are best for showing changes over time.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A pie chart should always show percentages that add up to 100%.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Pie charts show parts of a whole, which must total 100%.",
        points: 10,
      },
    ],
  },

  // Grade 5 Technology - Spreadsheets
  "5-spreadsheets": {
    id: "5-spreadsheets-quiz",
    title: "Spreadsheets Quiz",
    instructions: "Learn about spreadsheet basics!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a cell in a spreadsheet?",
        options: ["A row", "A column", "The box where a row and column meet", "A formula"],
        correctAnswer: "The box where a row and column meet",
        explanation: "A cell is the intersection of a row and column, like A1 or B3.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "In a spreadsheet, columns are labeled with ___ (letters or numbers).",
        correctAnswer: "letters",
        explanation: "Columns are A, B, C, etc. Rows are 1, 2, 3, etc.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What symbol typically starts a formula in a spreadsheet?",
        options: ["#", "=", "@", "$"],
        correctAnswer: "=",
        explanation: "Formulas start with = like =A1+B1 or =SUM(A1:A10)",
        points: 10,
      },
    ],
  },

  // Science - Atoms
  "7-atoms": {
    id: "7-atoms-quiz",
    title: "Atomic Structure Quiz",
    instructions: "Test your knowledge of atoms and their structure!",
    passingScore: 70,
    showExplanations: true,
    allowRetry: true,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What are the three main particles that make up an atom?",
        options: [
          "Protons, neutrons, and electrons",
          "Protons, neurons, and electrons",
          "Positrons, neutrons, and electrons",
          "Protons, neutrons, and positrons",
        ],
        correctAnswer: "Protons, neutrons, and electrons",
        explanation: "Atoms consist of protons (positive), neutrons (neutral), and electrons (negative).",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match each particle to its charge:",
        options: ["Proton", "Neutron", "Electron"],
        matchTargets: ["Positive (+)", "Neutral (0)", "Negative (-)"],
        correctAnswer: ["Positive (+)", "Neutral (0)", "Negative (-)"],
        explanation: "Protons are positive, neutrons have no charge, and electrons are negative.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Electrons orbit the nucleus of an atom.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Electrons move around the nucleus in regions called electron shells or orbitals.",
        points: 10,
      },
      {
        id: "q4",
        type: "fill_blank",
        question: "The center of an atom is called the ___.",
        correctAnswer: "nucleus",
        explanation: "The nucleus is the central core of an atom, containing protons and neutrons.",
        points: 10,
      },
      {
        id: "q5",
        type: "multiple_choice",
        question: "What determines the element of an atom?",
        options: [
          "Number of electrons",
          "Number of neutrons",
          "Number of protons",
          "Size of the nucleus",
        ],
        correctAnswer: "Number of protons",
        explanation: "The atomic number (number of protons) determines what element an atom is.",
        points: 15,
      },
    ],
  },
};

/**
 * Get quiz configuration for a lesson
 */
export function getQuizForLesson(lessonId: string): QuizConfig | null {
  return quizConfigs[lessonId] ?? null;
}

/**
 * Check if a lesson has a quiz
 */
export function hasQuiz(lessonId: string): boolean {
  return lessonId in quizConfigs;
}

/**
 * Get all available quiz IDs
 */
export function getAllQuizIds(): string[] {
  return Object.keys(quizConfigs);
}
