import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade7Quizzes: Record<string, QuizConfig> = {
  "7-add-sub-integers": createQuizConfig({
    id: "7-add-sub-integers-quiz",
    title: "Integer Operations Quiz",
    instructions: "Add and subtract positive and negative numbers.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is -5 + 3?",
        options: ["-8", "-2", "2", "8"],
        correctAnswer: "-2",
        explanation: "Starting at -5, moving 3 steps right gives -2.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "(-7) - (-4) = ___",
        correctAnswer: "-3",
        explanation: "Subtracting a negative is adding: -7 + 4 = -3.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is -8 + (-6)?",
        options: ["-14", "-2", "2", "14"],
        correctAnswer: "-14",
        explanation: "Adding two negatives: combine and keep the negative.",
        points: 10,
      },
    ],
  }),

  "7-two-step-equations": createQuizConfig({
    id: "7-two-step-equations-quiz",
    title: "Two-Step Equations Quiz",
    instructions: "Solve equations with two operations.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Solve: 2x + 5 = 13",
        options: ["x = 4", "x = 9", "x = 6", "x = 3"],
        correctAnswer: "x = 4",
        explanation: "2x + 5 = 13 -> 2x = 8 -> x = 4.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If 3y - 7 = 11, then y = ___.",
        correctAnswer: "6",
        explanation: "3y - 7 = 11 -> 3y = 18 -> y = 6.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Solve: x/4 + 3 = 7",
        options: ["x = 10", "x = 16", "x = 1", "x = 4"],
        correctAnswer: "x = 16",
        explanation: "x/4 + 3 = 7 -> x/4 = 4 -> x = 16.",
        points: 15,
      },
    ],
  }),

  "7-inequalities": createQuizConfig({
    id: "7-inequalities-quiz",
    title: "Inequalities Quiz",
    instructions: "Solve and graph inequalities.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which value satisfies x > 5?",
        options: ["3", "5", "7", "4"],
        correctAnswer: "7",
        explanation: "7 is greater than 5, so it satisfies x > 5.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "When you multiply both sides of an inequality by a negative number, you must flip the inequality sign.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Multiplying or dividing by a negative reverses the inequality.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Solve: x - 3 <= 7",
        options: ["x <= 4", "x <= 10", "x >= 10", "x <= -4"],
        correctAnswer: "x <= 10",
        explanation: "Add 3 to both sides: x <= 10.",
        points: 10,
      },
    ],
  }),

  "7-point-of-view-effects": createQuizConfig({
    id: "7-point-of-view-effects-quiz",
    title: "Point of View Effects Quiz",
    instructions: "Analyze how point of view affects a story.",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the point of view to its characteristics:",
        options: ["First person", "Third person limited", "Third person omniscient"],
        matchTargets: ["Uses 'I' and 'me'", "Knows one character's thoughts", "Knows all characters' thoughts"],
        correctAnswer: ["Uses 'I' and 'me'", "Knows one character's thoughts", "Knows all characters' thoughts"],
        explanation: "Each POV provides different levels of access to characters' minds.",
        points: 15,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "How does first-person narration affect a story?",
        options: ["We know everyone's thoughts", "We only see one character's perspective", "The narrator knows everything", "It's always unreliable"],
        correctAnswer: "We only see one character's perspective",
        explanation: "First person limits us to one character's experiences and knowledge.",
        points: 10,
      },
    ],
  }),

  "7-digestive": createQuizConfig({
    id: "7-digestive-quiz",
    title: "Digestive System Quiz",
    instructions: "Test your knowledge of digestion.",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Order the path of food through the digestive system:",
        options: ["Small intestine", "Stomach", "Mouth", "Large intestine", "Esophagus"],
        correctAnswer: ["Mouth", "Esophagus", "Stomach", "Small intestine", "Large intestine"],
        explanation: "Food travels through these organs in this specific order.",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Where does most nutrient absorption occur?",
        options: ["Stomach", "Small intestine", "Large intestine", "Mouth"],
        correctAnswer: "Small intestine",
        explanation: "The small intestine's villi absorb most nutrients into the bloodstream.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The ___ produces bile to help digest fats.",
        correctAnswer: "liver",
        explanation: "The liver makes bile, which is stored in the gallbladder.",
        points: 10,
      },
    ],
  }),

  "7-elements": createQuizConfig({
    id: "7-elements-quiz",
    title: "Elements & Periodic Table Quiz",
    instructions: "Explore the periodic table.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the chemical symbol for gold?",
        options: ["Go", "Gd", "Au", "Ag"],
        correctAnswer: "Au",
        explanation: "Au comes from the Latin word 'aurum' meaning gold.",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match the element to its symbol:",
        options: ["Oxygen", "Carbon", "Sodium", "Iron"],
        matchTargets: ["O", "C", "Na", "Fe"],
        correctAnswer: ["O", "C", "Na", "Fe"],
        explanation: "Some symbols come from Latin names (Na=Natrium, Fe=Ferrum).",
        points: 20,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The periodic table organizes elements by atomic ___.",
        correctAnswer: "number",
        explanation: "Elements are arranged by increasing atomic number (number of protons).",
        points: 10,
      },
    ],
  }),

  "7-middle-ages": createQuizConfig({
    id: "7-middle-ages-quiz",
    title: "Middle Ages Quiz",
    instructions: "Explore medieval Europe.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "The feudal system was based on:",
        options: ["Democracy", "Land ownership and loyalty", "Trade and commerce", "Religious authority"],
        correctAnswer: "Land ownership and loyalty",
        explanation: "Feudalism exchanged land for military service and loyalty.",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Order the feudal hierarchy from highest to lowest:",
        options: ["Peasants", "Knights", "King", "Lords"],
        correctAnswer: ["King", "Lords", "Knights", "Peasants"],
        explanation: "The king was at the top, with lords, knights, and peasants below.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The Crusades were religious wars to capture the Holy Land.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "The Crusades (1095-1291) were military campaigns to reclaim Jerusalem.",
        points: 10,
      },
    ],
  }),

  "7-python-intro": createQuizConfig({
    id: "7-python-intro-quiz",
    title: "Python Introduction Quiz",
    instructions: "Test your Python basics.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How do you print 'Hello World' in Python?",
        options: ["echo 'Hello World'", "print('Hello World')", "console.log('Hello World')", "System.out.println('Hello World')"],
        correctAnswer: "print('Hello World')",
        explanation: "Python uses the print() function to display output.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "In Python, you create a variable like this: name = 'Alice'. The value 'Alice' is a ___.",
        correctAnswer: "string",
        explanation: "Text enclosed in quotes is called a string.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Python uses indentation to define code blocks.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Unlike other languages, Python uses indentation instead of braces {}.",
        points: 10,
      },
    ],
  }),
};
