import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade6Quizzes: Record<string, QuizConfig> = {
  "6-ratios-intro": createQuizConfig({
    id: "6-ratios-intro-quiz",
    title: "Understanding Ratios Quiz",
    instructions: "Test your knowledge of ratios and proportions.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If there are 3 red marbles and 5 blue marbles, what is the ratio of red to blue?",
        options: ["3:5", "5:3", "3:8", "8:3"],
        correctAnswer: "3:5",
        explanation: "A ratio compares two quantities in order. Red to blue is 3:5.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "A ratio of 4:8 simplified equals ___:2.",
        correctAnswer: "1",
        explanation: "4:8 simplifies to 1:2 by dividing both numbers by 4.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If a recipe uses 2 cups flour for 12 cookies, how many cups for 36 cookies?",
        options: ["4 cups", "6 cups", "8 cups", "3 cups"],
        correctAnswer: "6 cups",
        explanation: "36 is 3x 12, so you need 3x 2 = 6 cups of flour.",
        points: 15,
      },
    ],
  }),

  "6-unit-rates": createQuizConfig({
    id: "6-unit-rates-quiz",
    title: "Unit Rates Quiz",
    instructions: "Calculate and apply unit rates.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If a car travels 240 miles in 4 hours, what is the unit rate (miles per hour)?",
        options: ["40 mph", "50 mph", "60 mph", "80 mph"],
        correctAnswer: "60 mph",
        explanation: "Unit rate = 240 / 4 = 60 miles per hour.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If 5 apples cost $2.50, each apple costs $___ .",
        correctAnswer: "0.50",
        explanation: "$2.50 / 5 = $0.50 per apple.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A unit rate always has 1 as the second quantity.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Unit rates express quantity 'per 1 unit' like $/mile or words/minute.",
        points: 10,
      },
    ],
  }),

  "6-percent": createQuizConfig({
    id: "6-percent-quiz",
    title: "Percent Quiz",
    instructions: "Solve problems involving percentages.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 25% of 80?",
        options: ["15", "20", "25", "40"],
        correctAnswer: "20",
        explanation: "25% = 0.25. 0.25 x 80 = 20.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If a $50 item is 20% off, the discount is $___.",
        correctAnswer: "10",
        explanation: "20% of $50 = 0.20 x 50 = $10.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "30 out of 50 students passed. What percent passed?",
        options: ["30%", "50%", "60%", "80%"],
        correctAnswer: "60%",
        explanation: "30/50 = 0.6 = 60%.",
        points: 15,
      },
    ],
  }),

  "6-exponents": createQuizConfig({
    id: "6-exponents-quiz",
    title: "Exponents Quiz",
    instructions: "Evaluate expressions with exponents.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 2 cubed?",
        options: ["6", "8", "9", "16"],
        correctAnswer: "8",
        explanation: "2 cubed = 2 x 2 x 2 = 8.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "5 squared equals ___.",
        correctAnswer: "25",
        explanation: "5 squared = 5 x 5 = 25.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which expression equals 10,000?",
        options: ["10 squared", "10 cubed", "10 to the 4th", "10 to the 5th"],
        correctAnswer: "10 to the 4th",
        explanation: "10 to the 4th = 10 x 10 x 10 x 10 = 10,000.",
        points: 15,
      },
    ],
  }),

  "6-one-step-equations": createQuizConfig({
    id: "6-one-step-equations-quiz",
    title: "One-Step Equations Quiz",
    instructions: "Solve equations with one operation.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Solve: x + 7 = 12",
        options: ["x = 5", "x = 7", "x = 19", "x = 12"],
        correctAnswer: "x = 5",
        explanation: "Subtract 7 from both sides: x = 12 - 7 = 5.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If 3x = 15, then x = ___.",
        correctAnswer: "5",
        explanation: "Divide both sides by 3: x = 15 / 3 = 5.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Solve: y - 4 = 9",
        options: ["y = 5", "y = 13", "y = 36", "y = 4"],
        correctAnswer: "y = 13",
        explanation: "Add 4 to both sides: y = 9 + 4 = 13.",
        points: 10,
      },
    ],
  }),

  "6-textual-evidence": createQuizConfig({
    id: "6-textual-evidence-quiz",
    title: "Textual Evidence Quiz",
    instructions: "Learn how to cite evidence from texts.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Textual evidence is:",
        options: ["Your personal opinion", "Quotes or paraphrases from the text", "What you think happened", "A summary"],
        correctAnswer: "Quotes or paraphrases from the text",
        explanation: "Textual evidence comes directly from the reading to support your claims.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "When citing textual evidence, you should use quotation marks around exact words from the text.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Quotation marks show which words came directly from the source.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which phrase best introduces textual evidence?",
        options: ["I think that...", "According to the text...", "I feel like...", "Maybe the author..."],
        correctAnswer: "According to the text...",
        explanation: "Phrases like 'According to the text' or 'The author states' properly introduce evidence.",
        points: 10,
      },
    ],
  }),

  "6-plot-development": createQuizConfig({
    id: "6-plot-development-quiz",
    title: "Plot Development Quiz",
    instructions: "Analyze how stories unfold.",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put the plot elements in order:",
        options: ["Climax", "Resolution", "Exposition", "Rising Action", "Falling Action"],
        correctAnswer: ["Exposition", "Rising Action", "Climax", "Falling Action", "Resolution"],
        explanation: "The plot follows this sequence from beginning to end.",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "The climax of a story is:",
        options: ["The beginning", "The most exciting turning point", "The conclusion", "Character introduction"],
        correctAnswer: "The most exciting turning point",
        explanation: "The climax is the moment of highest tension where the main conflict is addressed.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The ___ introduces characters and setting at the beginning of a story.",
        correctAnswer: "exposition",
        explanation: "Exposition provides background information readers need to understand the story.",
        points: 10,
      },
    ],
  }),

  "6-cell-structure": createQuizConfig({
    id: "6-cell-structure-quiz",
    title: "Cell Structure Quiz",
    instructions: "Test your knowledge of cell organelles.",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match each organelle to its function:",
        options: ["Nucleus", "Mitochondria", "Cell membrane", "Ribosomes"],
        matchTargets: ["Controls the cell", "Makes energy", "Controls what enters/exits", "Makes proteins"],
        correctAnswer: ["Controls the cell", "Makes energy", "Controls what enters/exits", "Makes proteins"],
        explanation: "Each organelle has a specific job in the cell.",
        points: 20,
      },
      {
        id: "q2",
        type: "true_false",
        question: "All cells have a nucleus.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Prokaryotic cells (like bacteria) don't have a nucleus.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The ___ are called the 'powerhouse' of the cell.",
        correctAnswer: "mitochondria",
        explanation: "Mitochondria produce ATP, the cell's energy currency.",
        points: 10,
      },
    ],
  }),

  "6-plant-animal-cells": createQuizConfig({
    id: "6-plant-animal-cells-quiz",
    title: "Plant vs Animal Cells Quiz",
    instructions: "Compare plant and animal cells.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which structure is found ONLY in plant cells?",
        options: ["Nucleus", "Cell wall", "Mitochondria", "Cell membrane"],
        correctAnswer: "Cell wall",
        explanation: "Plant cells have a rigid cell wall; animal cells do not.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Both plant and animal cells have chloroplasts.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Only plant cells have chloroplasts for photosynthesis.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What do chloroplasts do?",
        options: ["Store water", "Convert sunlight to food", "Protect the cell", "Make proteins"],
        correctAnswer: "Convert sunlight to food",
        explanation: "Chloroplasts perform photosynthesis, converting light energy to glucose.",
        points: 10,
      },
    ],
  }),

  "6-solar-system": createQuizConfig({
    id: "6-solar-system-quiz",
    title: "Solar System Quiz",
    instructions: "Explore our solar system!",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Order the planets from closest to farthest from the Sun:",
        options: ["Earth", "Mars", "Mercury", "Venus"],
        correctAnswer: ["Mercury", "Venus", "Earth", "Mars"],
        explanation: "The inner planets in order are Mercury, Venus, Earth, Mars.",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which planet is known as the 'Red Planet'?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        explanation: "Mars appears red due to iron oxide (rust) on its surface.",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "The largest planet in our solar system is ___.",
        correctAnswer: "Jupiter",
        explanation: "Jupiter is so large that all other planets could fit inside it.",
        points: 10,
      },
    ],
  }),

  "6-greece": createQuizConfig({
    id: "6-greece-quiz",
    title: "Ancient Greece Quiz",
    instructions: "Test your knowledge of ancient Greek civilization.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which Greek city-state was known for its powerful military?",
        options: ["Athens", "Sparta", "Corinth", "Thebes"],
        correctAnswer: "Sparta",
        explanation: "Sparta was famous for its disciplined military society.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Democracy was invented in ancient Greece.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Athens developed the first known democracy around 500 BCE.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "The Olympic Games originated in:",
        options: ["Rome", "Egypt", "Greece", "Persia"],
        correctAnswer: "Greece",
        explanation: "The ancient Olympics began in Olympia, Greece around 776 BCE.",
        points: 10,
      },
    ],
  }),

  "6-rome": createQuizConfig({
    id: "6-rome-quiz",
    title: "Ancient Rome Quiz",
    instructions: "Explore the Roman Empire.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What form of government did Rome have before becoming an empire?",
        options: ["Democracy", "Monarchy", "Republic", "Dictatorship"],
        correctAnswer: "Republic",
        explanation: "Rome was a republic with elected officials before becoming an empire.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "Julius ___ was a famous Roman leader who was assassinated in 44 BCE.",
        correctAnswer: "Caesar",
        explanation: "Julius Caesar's assassination led to the end of the Roman Republic.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The Colosseum was used for gladiator fights.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "The Colosseum hosted gladiatorial games and public spectacles.",
        points: 10,
      },
    ],
  }),

  "6-html-basics": createQuizConfig({
    id: "6-html-basics-quiz",
    title: "HTML Basics Quiz",
    instructions: "Test your knowledge of HTML web structure.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What does HTML stand for?",
        options: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "High Tech Modern Language"],
        correctAnswer: "Hyper Text Markup Language",
        explanation: "HTML is the standard language for creating web pages.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The <h1> tag creates a main ___.",
        correctAnswer: "heading",
        explanation: "The h1 tag is the largest heading tag in HTML.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which tag creates a paragraph?",
        options: ["<para>", "<p>", "<text>", "<paragraph>"],
        correctAnswer: "<p>",
        explanation: "The <p> tag defines a paragraph in HTML.",
        points: 10,
      },
    ],
  }),

  "6-css-styling": createQuizConfig({
    id: "6-css-styling-quiz",
    title: "CSS Styling Quiz",
    instructions: "Learn about styling web pages.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What does CSS stand for?",
        options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style Sheets", "Colorful Style Sheets"],
        correctAnswer: "Cascading Style Sheets",
        explanation: "CSS is used to style and layout web pages.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "To change text color in CSS, you use the ___ property.",
        correctAnswer: "color",
        explanation: "The color property sets the text color: color: blue;",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "CSS can change the font, colors, and layout of a webpage.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "CSS controls the visual presentation of HTML elements.",
        points: 10,
      },
    ],
  }),
};
