import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade8Quizzes: Record<string, QuizConfig> = {
  "8-linear-equations-one": createQuizConfig({
    id: "8-linear-equations-one-quiz",
    title: "Linear Equations Quiz",
    instructions: "Solve linear equations.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Solve: 3x - 7 = 2x + 5",
        options: ["x = 12", "x = -12", "x = 2", "x = -2"],
        correctAnswer: "x = 12",
        explanation: "3x - 7 = 2x + 5 -> x - 7 = 5 -> x = 12.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "Solve: 2(x + 4) = 14. x = ___",
        correctAnswer: "3",
        explanation: "2(x + 4) = 14 -> x + 4 = 7 -> x = 3.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which equation has infinitely many solutions?",
        options: ["x + 2 = x + 3", "2x = 2x", "3x = 9", "x = 5"],
        correctAnswer: "2x = 2x",
        explanation: "When both sides are identical, any value of x works.",
        points: 15,
      },
    ],
  }),

  "8-systems": createQuizConfig({
    id: "8-systems-quiz",
    title: "Systems of Equations Quiz",
    instructions: "Solve systems of linear equations.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Solve: x + y = 10 and x - y = 4. What is x?",
        options: ["3", "5", "7", "10"],
        correctAnswer: "7",
        explanation: "Adding the equations: 2x = 14, so x = 7.",
        points: 15,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A system of equations with the same slope but different y-intercepts has no solution.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Parallel lines never intersect, so there's no solution.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What does the solution to a system of equations represent graphically?",
        options: ["The y-intercept", "The slope", "The point where lines intersect", "The x-intercept"],
        correctAnswer: "The point where lines intersect",
        explanation: "The solution is the (x, y) coordinate where both lines meet.",
        points: 10,
      },
    ],
  }),

  "8-functions-intro": createQuizConfig({
    id: "8-functions-intro-quiz",
    title: "Understanding Functions Quiz",
    instructions: "Learn about functions and their properties.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "A function is a relationship where:",
        options: ["Each input has exactly one output", "Each output has exactly one input", "Inputs and outputs are the same", "There are no rules"],
        correctAnswer: "Each input has exactly one output",
        explanation: "In a function, every x-value maps to exactly one y-value.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "In f(x) = 2x + 3, f(4) = ___.",
        correctAnswer: "11",
        explanation: "f(4) = 2(4) + 3 = 8 + 3 = 11.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A vertical line test can determine if a graph represents a function.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "If a vertical line crosses the graph more than once, it's not a function.",
        points: 10,
      },
    ],
  }),

  "8-pythagorean": createQuizConfig({
    id: "8-pythagorean-quiz",
    title: "Pythagorean Theorem Quiz",
    instructions: "Apply the Pythagorean theorem.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In a right triangle, if a = 3 and b = 4, what is c (the hypotenuse)?",
        options: ["5", "7", "12", "25"],
        correctAnswer: "5",
        explanation: "c squared = 3 squared + 4 squared = 9 + 16 = 25, so c = 5.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The Pythagorean theorem is a squared + b squared = ___ squared.",
        correctAnswer: "c",
        explanation: "The sum of squares of legs equals the square of the hypotenuse.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The Pythagorean theorem only works for right triangles.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "The theorem specifically applies to triangles with a 90 degree angle.",
        points: 10,
      },
    ],
  }),

  "8-historical-fiction": createQuizConfig({
    id: "8-historical-fiction-quiz",
    title: "Historical Fiction Quiz",
    instructions: "Analyze historical fiction elements.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Historical fiction is characterized by:",
        options: ["Only real events and people", "Fictional characters in real historical settings", "Completely imaginary worlds", "Future predictions"],
        correctAnswer: "Fictional characters in real historical settings",
        explanation: "Historical fiction blends fictional stories with real historical contexts.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Authors of historical fiction must research the time period they write about.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Accurate historical details make the fiction believable.",
        points: 10,
      },
    ],
  }),

  "8-motion": createQuizConfig({
    id: "8-motion-quiz",
    title: "Motion Quiz",
    instructions: "Describe and calculate motion.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Speed is calculated by:",
        options: ["Distance x Time", "Distance / Time", "Time / Distance", "Distance + Time"],
        correctAnswer: "Distance / Time",
        explanation: "Speed = Distance / Time (e.g., miles per hour).",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If a car travels 100 miles in 2 hours, its average speed is ___ mph.",
        correctAnswer: "50",
        explanation: "100 miles / 2 hours = 50 mph.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Velocity differs from speed because velocity includes:",
        options: ["Mass", "Direction", "Acceleration", "Time"],
        correctAnswer: "Direction",
        explanation: "Velocity is speed with a direction (e.g., 50 mph north).",
        points: 10,
      },
    ],
  }),

  "8-forces": createQuizConfig({
    id: "8-forces-quiz",
    title: "Newton's Laws Quiz",
    instructions: "Understand Newton's Laws of Motion.",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match each law to its description:",
        options: ["Newton's 1st Law", "Newton's 2nd Law", "Newton's 3rd Law"],
        matchTargets: ["Objects in motion stay in motion", "F = ma", "Every action has an equal and opposite reaction"],
        correctAnswer: ["Objects in motion stay in motion", "F = ma", "Every action has an equal and opposite reaction"],
        explanation: "These three laws form the foundation of classical mechanics.",
        points: 15,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "Newton's first law is also called the law of ___.",
        correctAnswer: "inertia",
        explanation: "Inertia is the tendency of objects to resist changes in motion.",
        points: 10,
      },
    ],
  }),

  "8-dna": createQuizConfig({
    id: "8-dna-quiz",
    title: "DNA Structure Quiz",
    instructions: "Explore DNA structure and function.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "DNA is shaped like a:",
        options: ["Straight ladder", "Double helix", "Single strand", "Circle"],
        correctAnswer: "Double helix",
        explanation: "DNA's famous double helix shape was discovered by Watson and Crick.",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match the DNA bases that pair together:",
        options: ["Adenine", "Cytosine"],
        matchTargets: ["Thymine", "Guanine"],
        correctAnswer: ["Thymine", "Guanine"],
        explanation: "A pairs with T, and C pairs with G.",
        points: 15,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "DNA stands for deoxyribonucleic ___.",
        correctAnswer: "acid",
        explanation: "DNA is deoxyribonucleic acid, the molecule carrying genetic information.",
        points: 10,
      },
    ],
  }),

  "8-civil-war": createQuizConfig({
    id: "8-civil-war-quiz",
    title: "Civil War Quiz",
    instructions: "Test your knowledge of the American Civil War.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "The main cause of the Civil War was:",
        options: ["Taxation", "Slavery and states' rights", "Foreign invasion", "Religion"],
        correctAnswer: "Slavery and states' rights",
        explanation: "Slavery was the central issue, intertwined with states' rights.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "Abraham ___ was president during the Civil War.",
        correctAnswer: "Lincoln",
        explanation: "Lincoln led the Union and issued the Emancipation Proclamation.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The Emancipation Proclamation freed all slaves in the Union states.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "It only freed slaves in Confederate states; border states kept slavery.",
        points: 10,
      },
    ],
  }),

  "8-threats": createQuizConfig({
    id: "8-threats-quiz",
    title: "Cyber Threats Quiz",
    instructions: "Learn about online security threats.",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the threat to its description:",
        options: ["Phishing", "Malware", "Ransomware"],
        matchTargets: ["Fake emails to steal info", "Harmful software", "Locks files for payment"],
        correctAnswer: ["Fake emails to steal info", "Harmful software", "Locks files for payment"],
        explanation: "Understanding threats helps you stay safe online.",
        points: 15,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Strong passwords should include letters, numbers, and symbols.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Complex passwords are harder for hackers to crack.",
        points: 10,
      },
    ],
  }),

  "8-encryption": createQuizConfig({
    id: "8-encryption-quiz",
    title: "Encryption Quiz",
    instructions: "Understand the basics of encryption.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Encryption is the process of:",
        options: ["Deleting data", "Converting data into a secret code", "Compressing files", "Downloading files"],
        correctAnswer: "Converting data into a secret code",
        explanation: "Encryption scrambles data so only authorized users can read it.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "HTTPS uses encryption to secure ___ browsing.",
        correctAnswer: "web",
        explanation: "The 'S' in HTTPS stands for 'Secure', indicating encrypted connections.",
        points: 10,
      },
    ],
  }),
};
