import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade4Quizzes: Record<string, QuizConfig> = {
  "4-multiply-2digit": createQuizConfig({
    id: "4-multiply-2digit-quiz",
    title: "Multi-Digit Multiplication Quiz",
    instructions: "Multiply larger numbers!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 23 x 4?",
        options: ["82", "92", "102", "112"],
        correctAnswer: "92",
        explanation: "23 x 4 = 92. Break it down: (20 x 4) + (3 x 4) = 80 + 12 = 92",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "45 x 3 = ___",
        correctAnswer: "135",
        explanation: "45 x 3 = 135. (40 x 3) + (5 x 3) = 120 + 15 = 135",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is 12 x 15?",
        options: ["150", "170", "180", "200"],
        correctAnswer: "180",
        explanation: "12 x 15 = 180. You can think: 12 x 10 = 120, 12 x 5 = 60, total = 180",
        points: 15,
      },
      {
        id: "q4",
        type: "true_false",
        question: "When multiplying by 10, you just add a zero to the end.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 24 x 10 = 240. The digits shift one place to the left.",
        points: 10,
      },
    ],
  }),

  "4-equivalent-fractions": createQuizConfig({
    id: "4-equivalent-fractions-quiz",
    title: "Equivalent Fractions Quiz",
    instructions: "Find fractions that are equal!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which fraction is equivalent to 1/2?",
        options: ["1/3", "2/4", "3/4", "1/4"],
        correctAnswer: "2/4",
        explanation: "1/2 = 2/4. Multiply both top and bottom by 2!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match equivalent fractions:",
        options: ["1/2", "1/3", "3/4"],
        matchTargets: ["2/4", "2/6", "6/8"],
        correctAnswer: ["2/4", "2/6", "6/8"],
        explanation: "Multiply or divide both parts by the same number to find equivalents.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "4/8 is equivalent to 1/2.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 4 / 4 = 1 and 8 / 4 = 2, so 4/8 = 1/2.",
        points: 10,
      },
    ],
  }),

  "4-decimals-intro": createQuizConfig({
    id: "4-decimals-intro-quiz",
    title: "Introduction to Decimals Quiz",
    instructions: "Learn about decimal numbers!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the decimal 0.5 equal to as a fraction?",
        options: ["1/2", "1/4", "1/5", "1/10"],
        correctAnswer: "1/2",
        explanation: "0.5 = 5/10 = 1/2 (five tenths equals one half)",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these decimals in order from smallest to largest:",
        options: ["0.7", "0.25", "0.5", "0.1"],
        correctAnswer: ["0.1", "0.25", "0.5", "0.7"],
        explanation: "0.1 < 0.25 < 0.5 < 0.7",
        points: 15,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "0.25 = ___/100 (write the numerator only)",
        correctAnswer: "25",
        explanation: "0.25 = 25/100 = 25 hundredths",
        points: 10,
      },
    ],
  }),

  "4-character-motivation": createQuizConfig({
    id: "4-character-motivation-quiz",
    title: "Character Motivation Quiz",
    instructions: "Understand why characters do what they do!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is character motivation?",
        options: ["What a character looks like", "Why a character acts a certain way", "Where a character lives", "What a character says"],
        correctAnswer: "Why a character acts a certain way",
        explanation: "Motivation is the reason behind a character's actions.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "If a character studies hard because they want to become a doctor, what is their motivation?",
        options: ["Fear", "Curiosity", "A goal or dream", "Laziness"],
        correctAnswer: "A goal or dream",
        explanation: "Their dream of becoming a doctor motivates them to study.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Characters can have more than one motivation.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Characters often have multiple reasons for their actions.",
        points: 10,
      },
    ],
  }),

  "4-opinion-writing": createQuizConfig({
    id: "4-opinion-writing-quiz",
    title: "Opinion Writing Quiz",
    instructions: "Learn to express your opinions in writing!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What should opinion writing include?",
        options: ["Just your opinion", "Your opinion with reasons", "Only facts", "A story"],
        correctAnswer: "Your opinion with reasons",
        explanation: "Good opinion writing states your opinion AND supports it with reasons!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which is an opinion?",
        options: ["Dogs are mammals", "The sun rises in the east", "Pizza is the best food", "Water freezes at 32 degrees F"],
        correctAnswer: "Pizza is the best food",
        explanation: "'Best' is a judgment - different people have different opinions!",
        points: 10,
      },
      {
        id: "q3",
        type: "ordering",
        question: "Put these parts of opinion writing in order:",
        options: ["Conclusion", "Introduction with opinion", "Reasons and examples", "Restate opinion"],
        correctAnswer: ["Introduction with opinion", "Reasons and examples", "Restate opinion", "Conclusion"],
        explanation: "Start with your opinion, give reasons, then wrap up!",
        points: 15,
      },
    ],
  }),

  "4-energy-forms": createQuizConfig({
    id: "4-energy-forms-quiz",
    title: "Forms of Energy Quiz",
    instructions: "Identify different types of energy!",
    questions: [
      {
        id: "q1",
        type: "matching",
        question: "Match the energy type to the example:",
        options: ["Light energy", "Sound energy", "Heat energy", "Electrical energy"],
        matchTargets: ["Sun shining", "Music playing", "Fire burning", "Lightning bolt"],
        correctAnswer: ["Sun shining", "Music playing", "Fire burning", "Lightning bolt"],
        explanation: "Energy comes in many forms and can change from one to another!",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What type of energy is stored in food?",
        options: ["Light energy", "Chemical energy", "Sound energy", "Motion energy"],
        correctAnswer: "Chemical energy",
        explanation: "Food contains chemical energy that our bodies convert to other forms.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Energy can be created from nothing.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Energy cannot be created or destroyed - it can only change forms!",
        points: 10,
      },
    ],
  }),

  "4-water-cycle": createQuizConfig({
    id: "4-water-cycle-quiz",
    title: "Water Cycle Quiz",
    instructions: "Learn about Earth's water cycle!",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put the water cycle steps in order:",
        options: ["Precipitation", "Evaporation", "Collection", "Condensation"],
        correctAnswer: ["Evaporation", "Condensation", "Precipitation", "Collection"],
        explanation: "Water evaporates -> condenses into clouds -> falls as rain -> collects in bodies of water",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What happens during evaporation?",
        options: ["Water falls from clouds", "Water turns to vapor and rises", "Clouds form", "Water freezes"],
        correctAnswer: "Water turns to vapor and rises",
        explanation: "Evaporation is when liquid water becomes water vapor (gas).",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "When water vapor cools and forms clouds, this is called ___.",
        correctAnswer: "condensation",
        explanation: "Condensation is when water vapor cools and turns back into tiny water droplets.",
        points: 10,
      },
    ],
  }),

  "4-northeast": createQuizConfig({
    id: "4-northeast-quiz",
    title: "Northeast Region Quiz",
    instructions: "What do you know about the Northeast?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which city in the Northeast is the largest in the United States?",
        options: ["Boston", "Philadelphia", "New York City", "Baltimore"],
        correctAnswer: "New York City",
        explanation: "New York City is the largest city in the US with over 8 million people!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "The Northeast region has all four seasons.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The Northeast experiences spring, summer, fall, and winter.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What ocean borders the Northeast region?",
        options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
        correctAnswer: "Atlantic Ocean",
        explanation: "The Atlantic Ocean is on the eastern coast of the Northeast.",
        points: 10,
      },
    ],
  }),

  "4-variables": createQuizConfig({
    id: "4-variables-quiz",
    title: "Variables in Coding Quiz",
    instructions: "Learn about variables in programming!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a variable in coding?",
        options: ["A type of loop", "A container that stores information", "A drawing tool", "A way to delete code"],
        correctAnswer: "A container that stores information",
        explanation: "Variables store data like numbers, text, or other information.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A variable can change its value during a program.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! That's why it's called a VARIable - it can vary or change.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If you have a variable called 'score' set to 10, and you add 5, what is the new value?",
        options: ["5", "10", "15", "50"],
        correctAnswer: "15",
        explanation: "10 + 5 = 15. The variable 'score' now holds 15.",
        points: 10,
      },
    ],
  }),

  "4-conditionals": createQuizConfig({
    id: "4-conditionals-quiz",
    title: "Conditionals Quiz",
    instructions: "Learn about if-then statements!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a conditional in coding?",
        options: ["A loop", "A decision that says 'if this, then that'", "A variable", "A comment"],
        correctAnswer: "A decision that says 'if this, then that'",
        explanation: "Conditionals let programs make decisions based on conditions.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "In 'IF it is raining THEN bring an umbrella,' what is the condition?",
        options: ["Bring an umbrella", "It is raining", "It is sunny", "Go outside"],
        correctAnswer: "It is raining",
        explanation: "The condition is what we check - 'it is raining' is being tested.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "An ELSE block runs when the IF condition is false.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! ELSE provides an alternative action when IF is not true.",
        points: 10,
      },
    ],
  }),
};
