import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade1Quizzes: Record<string, QuizConfig> = {
  "1-tens-ones": createQuizConfig({
    id: "1-tens-ones-quiz",
    title: "Tens and Ones Quiz",
    instructions: "Let's learn about place value!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In the number 25, how many tens are there?",
        options: ["2", "5", "25", "7"],
        correctAnswer: "2",
        explanation: "25 has 2 tens (20) and 5 ones (5). 20 + 5 = 25!",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "The number 34 has 3 tens and ___ ones.",
        correctAnswer: "4",
        explanation: "34 = 30 + 4, so there are 4 ones!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What number has 4 tens and 7 ones?",
        options: ["47", "74", "11", "41"],
        correctAnswer: "47",
        explanation: "4 tens = 40, plus 7 ones = 47!",
        points: 10,
      },
      {
        id: "q4",
        type: "true_false",
        question: "The number 50 has 5 tens and 0 ones.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! 50 = 5 tens (50) + 0 ones.",
        points: 10,
      },
    ],
  }),

  "1-add-within-20": createQuizConfig({
    id: "1-add-within-20-quiz",
    title: "Addition within 20 Quiz",
    instructions: "Practice adding numbers up to 20!",
    questions: [
      {
        id: "q1",
        type: "fill_blank",
        question: "8 + 5 = ___",
        correctAnswer: "13",
        explanation: "8 + 5 = 13. You can count on: 8... 9, 10, 11, 12, 13!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What is 9 + 7?",
        options: ["14", "15", "16", "17"],
        correctAnswer: "16",
        explanation: "9 + 7 = 16. Think: 9 + 1 = 10, then 10 + 6 = 16!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which addition equals 15?",
        options: ["6 + 8", "7 + 8", "9 + 5", "8 + 8"],
        correctAnswer: "7 + 8",
        explanation: "7 + 8 = 15!",
        points: 15,
      },
    ],
  }),

  "1-short-vowels": createQuizConfig({
    id: "1-short-vowels-quiz",
    title: "Short Vowels Quiz",
    instructions: "Listen for short vowel sounds!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which word has a short 'a' sound?",
        options: ["cake", "cat", "car", "cape"],
        correctAnswer: "cat",
        explanation: "Cat has the short 'a' sound like in 'apple'!",
        points: 10,
      },
      {
        id: "q2",
        type: "matching",
        question: "Match words with the same short vowel sound:",
        options: ["bed", "pig", "hot"],
        matchTargets: ["short e", "short i", "short o"],
        correctAnswer: ["short e", "short i", "short o"],
        explanation: "Bed has short e, pig has short i, hot has short o!",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "The word 'cup' has a short 'u' sound.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Cup has the short 'u' sound like in 'umbrella'.",
        points: 10,
      },
    ],
  }),

  "1-light-sources": createQuizConfig({
    id: "1-light-sources-quiz",
    title: "Light Sources Quiz",
    instructions: "Where does light come from?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the biggest source of light for Earth?",
        options: ["Moon", "Stars", "Sun", "Lamp"],
        correctAnswer: "Sun",
        explanation: "The Sun is our biggest and brightest source of light!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "A flashlight makes its own light.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! A flashlight is a light source - it makes light!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which is NOT a light source?",
        options: ["Candle", "Mirror", "Lamp", "Fire"],
        correctAnswer: "Mirror",
        explanation: "A mirror reflects light but doesn't make its own light.",
        points: 15,
      },
    ],
  }),

  "1-day-night": createQuizConfig({
    id: "1-day-night-quiz",
    title: "Day and Night Quiz",
    instructions: "Why do we have day and night?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What makes daytime bright?",
        options: ["Moon", "Sun", "Stars", "Clouds"],
        correctAnswer: "Sun",
        explanation: "The Sun shines on Earth and makes daytime bright!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Earth spins around, which causes day and night.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! As Earth spins, different parts face the Sun.",
        points: 10,
      },
      {
        id: "q3",
        type: "ordering",
        question: "Put these in order from morning to night:",
        options: ["Sunset", "Sunrise", "Noon", "Midnight"],
        correctAnswer: ["Sunrise", "Noon", "Sunset", "Midnight"],
        explanation: "A day goes: sunrise, noon, sunset, midnight!",
        points: 20,
      },
    ],
  }),

  "1-rules-laws": createQuizConfig({
    id: "1-rules-laws-quiz",
    title: "Rules and Laws Quiz",
    instructions: "Why do we have rules?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Why do we have rules?",
        options: ["To have fun", "To keep us safe", "To make us sad", "To waste time"],
        correctAnswer: "To keep us safe",
        explanation: "Rules help keep everyone safe and things fair!",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "It's a rule to raise your hand before speaking in class.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! This rule helps everyone get a turn to speak.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is a law?",
        options: ["A game", "A rule made by the government", "A toy", "A book"],
        correctAnswer: "A rule made by the government",
        explanation: "Laws are rules that everyone in a community must follow.",
        points: 15,
      },
    ],
  }),

  "1-internet-safety": createQuizConfig({
    id: "1-internet-safety-quiz",
    title: "Internet Safety Quiz",
    instructions: "Stay safe online!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Should you share your password with friends?",
        options: ["Yes, always", "No, never", "Only best friends", "Only online"],
        correctAnswer: "No, never",
        explanation: "Passwords are secret! Only share with parents.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "You should tell a grown-up if something online makes you feel scared or sad.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Always tell a trusted adult if something online upsets you.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What should you NOT share online?",
        options: ["Your favorite color", "Your full name and address", "Your favorite animal", "Your hobby"],
        correctAnswer: "Your full name and address",
        explanation: "Never share personal info like your full name, address, or school online!",
        points: 15,
      },
    ],
  }),
};
