import { createQuizConfig } from "../defaults";
import type { QuizConfig } from "../../types";

export const grade3Quizzes: Record<string, QuizConfig> = {
  "3-mult-intro": createQuizConfig({
    id: "3-mult-intro-quiz",
    title: "Introduction to Multiplication Quiz",
    instructions: "Show what you learned about multiplication!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is 3 x 4?",
        options: ["7", "10", "12", "14"],
        correctAnswer: "12",
        explanation: "3 x 4 means 3 groups of 4, which equals 12.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "5 x 2 = ___",
        correctAnswer: "10",
        explanation: "5 x 2 = 10. Think of it as 5 + 5!",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "If you have 4 bags with 3 apples in each bag, how many apples do you have in total?",
        options: ["7", "10", "12", "15"],
        correctAnswer: "12",
        explanation: "4 bags x 3 apples = 12 apples total.",
        points: 15,
      },
      {
        id: "q4",
        type: "true_false",
        question: "2 x 6 gives the same answer as 6 x 2.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! This is called the commutative property. Order doesn't matter in multiplication.",
        points: 10,
      },
      {
        id: "q5",
        type: "ordering",
        question: "Put these products in order from smallest to largest:",
        options: ["2x5", "3x3", "4x2", "1x6"],
        correctAnswer: ["1x6", "4x2", "3x3", "2x5"],
        explanation: "1x6=6, 4x2=8, 3x3=9, 2x5=10. So the order is: 6, 8, 9, 10.",
        points: 15,
      },
    ],
  }),

  "3-fractions-intro": createQuizConfig({
    id: "3-fractions-intro-quiz",
    title: "Introduction to Fractions Quiz",
    instructions: "Test your understanding of fractions!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If a pizza is cut into 4 equal pieces and you eat 1 piece, what fraction did you eat?",
        options: ["1/2", "1/3", "1/4", "1/5"],
        correctAnswer: "1/4",
        explanation: "You ate 1 piece out of 4 equal pieces, which is 1/4 (one-fourth).",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In the fraction 3/4, the number 3 is called the numerator.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "The top number in a fraction is called the numerator. The bottom number is the denominator.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which fraction is larger: 1/2 or 1/4?",
        options: ["1/2", "1/4", "They are equal"],
        correctAnswer: "1/2",
        explanation: "1/2 is larger because when you divide something into fewer pieces, each piece is bigger!",
        points: 10,
      },
      {
        id: "q4",
        type: "fill_blank",
        question: "If you have 2/4 of a pie, that's the same as having ___ (write as a fraction like 1/2)",
        correctAnswer: "1/2",
        explanation: "2/4 = 1/2. These are equivalent fractions!",
        points: 15,
      },
    ],
  }),

  "3-solar-system": createQuizConfig({
    id: "3-solar-system-quiz",
    title: "Solar System Quiz",
    instructions: "Answer questions about our solar system!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is at the center of our solar system?",
        options: ["Earth", "Moon", "Sun", "Mars"],
        correctAnswer: "Sun",
        explanation: "The Sun is a star at the center of our solar system. All planets orbit around it.",
        points: 10,
      },
      {
        id: "q2",
        type: "ordering",
        question: "Put these planets in order from closest to the Sun to farthest:",
        options: ["Earth", "Mars", "Venus", "Mercury"],
        correctAnswer: ["Mercury", "Venus", "Earth", "Mars"],
        explanation: "The order from the Sun is: Mercury, Venus, Earth, Mars (the inner rocky planets).",
        points: 20,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Earth is the only planet in our solar system with a moon.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Many planets have moons! Mars has 2, Jupiter has at least 95, and Saturn has over 140!",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "Which planet is known as the 'Red Planet'?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        explanation: "Mars is called the Red Planet because of the iron oxide (rust) on its surface.",
        points: 10,
      },
    ],
  }),

  "3-mult-facts": createQuizConfig({
    id: "3-mult-facts-quiz",
    title: "Multiplication Facts Quiz",
    instructions: "Practice your multiplication facts!",
    questions: [
      {
        id: "q1",
        type: "fill_blank",
        question: "7 x 8 = ___",
        correctAnswer: "56",
        explanation: "7 x 8 = 56. This is one of the trickier facts to memorize!",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What is 9 x 6?",
        options: ["45", "54", "56", "63"],
        correctAnswer: "54",
        explanation: "9 x 6 = 54. A trick: 9 x 6 = 54 (5 + 4 = 9).",
        points: 10,
      },
      {
        id: "q3",
        type: "fill_blank",
        question: "6 x 7 = ___",
        correctAnswer: "42",
        explanation: "6 x 7 = 42. Remember: 6, 7, 8... 6 x 7 = 42!",
        points: 10,
      },
      {
        id: "q4",
        type: "matching",
        question: "Match each multiplication to its product:",
        options: ["8 x 8", "9 x 9", "7 x 7", "6 x 6"],
        matchTargets: ["64", "81", "49", "36"],
        correctAnswer: ["64", "81", "49", "36"],
        explanation: "These are all perfect squares!",
        points: 20,
      },
    ],
  }),

  "3-division-intro": createQuizConfig({
    id: "3-division-intro-quiz",
    title: "Introduction to Division Quiz",
    instructions: "Show what you know about division!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "12 / 3 = ?",
        options: ["3", "4", "5", "6"],
        correctAnswer: "4",
        explanation: "12 / 3 = 4. Think: how many groups of 3 make 12?",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "20 / 4 = ___",
        correctAnswer: "5",
        explanation: "20 / 4 = 5. You can share 20 items equally among 4 people.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Division is the opposite of multiplication.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Division and multiplication are inverse operations.",
        points: 10,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "If you have 24 cookies and want to share them equally among 6 friends, how many cookies does each friend get?",
        options: ["3", "4", "5", "6"],
        correctAnswer: "4",
        explanation: "24 / 6 = 4 cookies per friend.",
        points: 15,
      },
    ],
  }),

  "3-theme": createQuizConfig({
    id: "3-theme-quiz",
    title: "Finding the Theme Quiz",
    instructions: "Answer questions about story themes!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is the theme of a story?",
        options: ["The main character", "The setting", "The main message or lesson", "The plot"],
        correctAnswer: "The main message or lesson",
        explanation: "The theme is the big idea or lesson the author wants you to learn.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "In a story where a character keeps trying until they succeed, what might the theme be?",
        options: ["Give up when things get hard", "Never give up", "Always ask for help", "Stay inside"],
        correctAnswer: "Never give up",
        explanation: "When a character perseveres, the theme is often about not giving up.",
        points: 15,
      },
      {
        id: "q3",
        type: "true_false",
        question: "A story can only have one theme.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Stories can have multiple themes or messages!",
        points: 10,
      },
    ],
  }),

  "3-point-of-view": createQuizConfig({
    id: "3-point-of-view-quiz",
    title: "Point of View Quiz",
    instructions: "Identify different points of view!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "If a story uses 'I' and 'me,' what point of view is it?",
        options: ["First person", "Second person", "Third person"],
        correctAnswer: "First person",
        explanation: "First person uses 'I,' 'me,' 'my' - the narrator is in the story.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "If a story uses 'he,' 'she,' and 'they,' what point of view is it?",
        options: ["First person", "Second person", "Third person"],
        correctAnswer: "Third person",
        explanation: "Third person uses 'he,' 'she,' 'they' - an outside narrator tells the story.",
        points: 10,
      },
      {
        id: "q3",
        type: "matching",
        question: "Match the pronoun to the point of view:",
        options: ["I went to school", "She went to school", "You went to school"],
        matchTargets: ["First person", "Third person", "Second person"],
        correctAnswer: ["First person", "Third person", "Second person"],
        explanation: "I = first, she/he = third, you = second person.",
        points: 15,
      },
    ],
  }),

  "3-friction": createQuizConfig({
    id: "3-friction-quiz",
    title: "Friction Quiz",
    instructions: "Test your knowledge about friction!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is friction?",
        options: ["A force that speeds things up", "A force that slows things down", "A type of energy", "A kind of motion"],
        correctAnswer: "A force that slows things down",
        explanation: "Friction is a force that opposes motion and slows things down.",
        points: 10,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "Which surface would have MORE friction?",
        options: ["Ice", "Sandpaper", "Glass", "Wet floor"],
        correctAnswer: "Sandpaper",
        explanation: "Rough surfaces like sandpaper create more friction than smooth surfaces.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Friction can produce heat.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Rub your hands together - the friction creates heat!",
        points: 10,
      },
    ],
  }),

  "3-magnets": createQuizConfig({
    id: "3-magnets-quiz",
    title: "Magnets Quiz",
    instructions: "What do you know about magnets?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What do we call the ends of a magnet?",
        options: ["Sides", "Poles", "Points", "Edges"],
        correctAnswer: "Poles",
        explanation: "Magnets have two poles: North and South.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Two north poles will attract each other.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Like poles repel! North-North or South-South push apart. Opposite poles attract.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "Which material would a magnet attract?",
        options: ["Wood", "Plastic", "Iron", "Glass"],
        correctAnswer: "Iron",
        explanation: "Magnets attract metals like iron, nickel, and cobalt.",
        points: 10,
      },
      {
        id: "q4",
        type: "matching",
        question: "Match the poles to what happens:",
        options: ["North + South", "North + North", "South + South"],
        matchTargets: ["Attract", "Repel", "Repel"],
        correctAnswer: ["Attract", "Repel", "Repel"],
        explanation: "Opposite poles attract, same poles repel!",
        points: 15,
      },
    ],
  }),

  "3-plant-life-cycle": createQuizConfig({
    id: "3-plant-life-cycle-quiz",
    title: "Plant Life Cycle Quiz",
    instructions: "Show what you know about how plants grow!",
    questions: [
      {
        id: "q1",
        type: "ordering",
        question: "Put the plant life cycle in order:",
        options: ["Adult plant", "Seed", "Seedling", "Flowering"],
        correctAnswer: ["Seed", "Seedling", "Adult plant", "Flowering"],
        explanation: "Seed -> Seedling -> Adult plant -> Flowering (then back to seeds!)",
        points: 20,
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "What do seeds need to germinate (start growing)?",
        options: ["Only sunlight", "Water, warmth, and air", "Only soil", "Only water"],
        correctAnswer: "Water, warmth, and air",
        explanation: "Seeds need water, warmth, and air to germinate.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "All plants produce flowers.",
        options: ["True", "False"],
        correctAnswer: "False",
        explanation: "Not all plants flower! Ferns and mosses reproduce differently.",
        points: 10,
      },
    ],
  }),

  "3-local-gov": createQuizConfig({
    id: "3-local-gov-quiz",
    title: "Local Government Quiz",
    instructions: "What do you know about your local government?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Who is usually the leader of a city?",
        options: ["President", "Governor", "Mayor", "Senator"],
        correctAnswer: "Mayor",
        explanation: "A mayor is the elected leader of a city or town.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "Local government takes care of things like parks and libraries.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Local governments run parks, libraries, fire departments, and more.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What is one way citizens can participate in local government?",
        options: ["Voting", "Moving away", "Ignoring laws", "Staying home"],
        correctAnswer: "Voting",
        explanation: "Voting is an important way to participate in democracy!",
        points: 10,
      },
    ],
  }),

  "3-block-coding": createQuizConfig({
    id: "3-block-coding-quiz",
    title: "Block Coding Quiz",
    instructions: "Test your coding knowledge!",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is block coding?",
        options: ["Building with blocks", "Programming with drag-and-drop blocks", "Playing video games", "Drawing pictures"],
        correctAnswer: "Programming with drag-and-drop blocks",
        explanation: "Block coding uses visual blocks you snap together to write programs.",
        points: 10,
      },
      {
        id: "q2",
        type: "true_false",
        question: "In block coding, the order of blocks matters.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! The computer follows blocks in order from top to bottom.",
        points: 10,
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "What does a 'repeat' block do?",
        options: ["Stops the program", "Runs code multiple times", "Deletes code", "Saves the program"],
        correctAnswer: "Runs code multiple times",
        explanation: "A repeat block runs the code inside it multiple times - this is called a loop!",
        points: 10,
      },
    ],
  }),

  "3-loops": createQuizConfig({
    id: "3-loops-quiz",
    title: "Loops Quiz",
    instructions: "What do you know about loops in coding?",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "What is a loop in coding?",
        options: ["A type of bug", "Code that repeats", "A way to stop code", "A drawing tool"],
        correctAnswer: "Code that repeats",
        explanation: "A loop repeats a set of instructions multiple times.",
        points: 10,
      },
      {
        id: "q2",
        type: "fill_blank",
        question: "If a loop says 'repeat 5 times,' the code inside runs ___ times.",
        correctAnswer: "5",
        explanation: "The code inside a 'repeat 5 times' loop runs exactly 5 times.",
        points: 10,
      },
      {
        id: "q3",
        type: "true_false",
        question: "Loops help make code shorter and easier to read.",
        options: ["True", "False"],
        correctAnswer: "True",
        explanation: "Yes! Instead of writing the same code 10 times, you use a loop.",
        points: 10,
      },
    ],
  }),
};
